### ISSUE TITLE
Dialogue session with invalid site_id after upgrade to 2.5.6

### ISSUE THREAD

**Issue by hawkeye217** [rhasspy/rhasspy#115]
I have a master/satellite configured and I upgraded my master to 2.5.6 today (from 2.5.0).  After upgrading, this shows in the container logs:

```
[DEBUG:2020-10-03 00:51:36,846] rhasspydialogue_hermes: Recognized NluIntent(input='what time is it', intent=Intent(intent_name='GetTime', confidence_score=1.0), site_id='framepi', id=None, slots=[], session_id='framepi-computer_activate-8970e96e-1f93-4c09-be07-713a7eee9f4c', custom_data=None, asr_tokens=[[AsrToken(value='what', confidence=1.0, range_start=0, range_end=4, time=None), AsrToken(value='time', confidence=1.0, range_start=5, range_end=9, time=None), AsrToken(value='is', confidence=1.0, range_start=10, range_end=12, time=None), AsrToken(value='it', confidence=1.0, range_start=13, range_end=15, time=None)]], asr_confidence=None, raw_input='what time is it', wakeword_id='computer_activate', lang=None)
[DEBUG:2020-10-03 00:51:36,849] rhasspydialogue_hermes: <- DialogueEndSession(session_id='framepi-computer_activate-8970e96e-1f93-4c09-be07-713a7eee9f4c', site_id='default', text=None, custom_data=None)
[ERROR:2020-10-03 00:51:36,849] asyncio: Task exception was never retrieved
future: <Task finished coro=<HermesClient.publish_all() done, defined at /usr/lib/rhasspy/rhasspy-hermes/rhasspyhermes/client.py:368> exception=AssertionError('No session at site default')>
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-hermes/rhasspyhermes/client.py", line 370, in publish_all
    async for maybe_message in async_generator:
  File "/usr/lib/rhasspy/rhasspy-dialogue-hermes/rhasspydialogue_hermes/__init__.py", line 705, in on_message
    async for end_result in self.handle_end(message):
  File "/usr/lib/rhasspy/rhasspy-dialogue-hermes/rhasspydialogue_hermes/__init__.py", line 394, in handle_end
    assert site_session is not None, f"No session at site {end_session.site_id}"
AssertionError: No session at site default
```

The ``site_id`` in the second debug line shows as "default" where I'm guessing it should be "framepi".  This has the side effect of not playing a TTS response.  Is this a bug or has something in the configuration changed between 2.5 and 2.5.6 that would cause this issue?

**Comment by synesthesiam** [comment]
Yes, there was a major change in the dialogue manager. Looks like I didn't catch all of the corner cases here; thanks for the report!

**Comment by synesthesiam** [comment]
I happen to be at my computer when you posted this, so I tried out an MQTT base/satellite set up again and it seems to be working for me.

Can you describe your set up a bit more please?

**Comment by hawkeye217** [comment]
Sure.  External MQTT broker for both. The master is configured with Kaldi, Fuzzywuzzy, and MaryTTS. Dialogue management set to "Rhasspy".  Satellite is configured with arecord, snowboy, and aplay.  If you need more specifics, let me know!

**Comment by Enc3ph4l0n** [comment]
Hi @synesthesiam,

I've had to implement workarounds for issues related to multiple sessions (https://community.rhasspy.org/t/maybe-a-bug-with-two-satellites/1378/2?u=enc3ph4l0n), so I'm really excited for these improvements. 

I have a master device configured for Kaldi and Fsticuffs, accompanied by 4 satellite devices. I've always ended the session myself after intent handling using:

```
MQTT.publish('hermes/dialogueManager/endSession', `{"sessionId": "${Session}"}`);
```

However, this causes the exact error as described above by the OP. The session eventually comes to an end by timeout. If I remove the end session code and leave it to Rhasspy dialog manager then I no longer get the error as above, but the session still doesn't end correctly - it always ends up in timeout - and I've tried on multiple satellites.

Furthermore, I've triggered two satellites at once with the hotword, but from my limited testing (because it's awkward) I've found neither satellite then captures anything I say. However, limited to a single satellite, between intent being recognised and before timeout I am able to retrigger the hotword to carry out another intent because the hotword is enabled twice it would seem.

I've captured some log information that I hope helps.

```
[DEBUG:2020-10-04 16:34:43,554] rhasspyasr_kaldi.transcribe: ['', "what's the date ", "what's the date "]
[DEBUG:2020-10-04 16:34:43,555] rhasspyasr_kaldi_hermes: Transcription result: Transcription(text="what's the date", likelihood=1, transcribe_seconds=1.3918036459945142, wav_seconds=1.984, tokens=None)
[DEBUG:2020-10-04 16:34:43,559] rhasspyasr_kaldi_hermes: -> AsrTextCaptured(text="what's the date", likelihood=1, seconds=1.3918036459945142, site_id='living-room', session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a', wakeword_id=None, asr_tokens=None, lang=None)
[DEBUG:2020-10-04 16:34:43,560] rhasspyasr_kaldi_hermes: Publishing 228 bytes(s) to hermes/asr/textCaptured
[DEBUG:2020-10-04 16:34:43,562] rhasspyasr_kaldi_hermes: -> AsrAudioCaptured(50924 byte(s)) to rhasspy/asr/living-room/living-room/audioCaptured
[DEBUG:2020-10-04 16:34:43,567] rhasspydialogue_hermes: <- AsrTextCaptured(text="what's the date", likelihood=1, seconds=1.3918036459945142, site_id='living-room', session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a', wakeword_id=None, asr_tokens=None, lang=None)
[DEBUG:2020-10-04 16:34:43,568] rhasspydialogue_hermes: Received text: what's the date
[DEBUG:2020-10-04 16:34:43,569] rhasspydialogue_hermes: -> AsrStopListening(site_id='living-room', session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a')
[DEBUG:2020-10-04 16:34:43,569] rhasspydialogue_hermes: Publishing 100 bytes(s) to hermes/asr/stopListening
[DEBUG:2020-10-04 16:34:43,572] rhasspydialogue_hermes: -> HotwordToggleOn(site_id='living-room', reason=<HotwordToggleReason.DIALOGUE_SESSION: 'dialogueSession'>)
[DEBUG:2020-10-04 16:34:43,573] rhasspydialogue_hermes: Publishing 54 bytes(s) to hermes/hotword/toggleOn
[DEBUG:2020-10-04 16:34:43,576] rhasspydialogue_hermes: -> NluQuery(input="what's the date", site_id='living-room', id=None, intent_filter=None, session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a', wakeword_id='bumblebee', lang=None)
[DEBUG:2020-10-04 16:34:43,577] rhasspydialogue_hermes: Publishing 203 bytes(s) to hermes/nlu/query
[DEBUG:2020-10-04 16:34:43,582] rhasspynlu_hermes: <- NluQuery(input="what's the date", site_id='living-room', id=None, intent_filter=None, session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a', wakeword_id='bumblebee', lang=None)
[DEBUG:2020-10-04 16:34:43,596] rhasspynlu_hermes: -> NluIntentParsed(input="what's the date", intent=Intent(intent_name='Date', confidence_score=1.0), site_id='living-room', id=None, slots=[], session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a')
[DEBUG:2020-10-04 16:34:43,601] rhasspyasr_kaldi_hermes: <- AsrStopListening(site_id='living-room', session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a')
[DEBUG:2020-10-04 16:34:43,602] rhasspyasr_kaldi_hermes: Stopping listening (session_id=living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a)
[DEBUG:2020-10-04 16:34:43,604] rhasspynlu_hermes: Publishing 211 bytes(s) to hermes/nlu/intentParsed
[DEBUG:2020-10-04 16:34:43,608] rhasspynlu_hermes: -> NluIntent(input="what's the date", intent=Intent(intent_name='Date', confidence_score=1.0), site_id='living-room', id=None, slots=[], session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a', custom_data=None, asr_tokens=[[AsrToken(value="what's", confidence=1.0, range_start=0, range_end=6, time=None), AsrToken(value='the', confidence=1.0, range_start=7, range_end=10, time=None), AsrToken(value='date', confidence=1.0, range_start=11, range_end=15, time=None)]], asr_confidence=None, raw_input="what's the date", wakeword_id='bumblebee', lang=None)
[DEBUG:2020-10-04 16:34:43,610] rhasspynlu_hermes: Publishing 599 bytes(s) to hermes/intent/Date
[DEBUG:2020-10-04 16:34:43,662] rhasspydialogue_hermes: <- NluIntent(input="what's the date", intent=Intent(intent_name='Date', confidence_score=1.0), site_id='living-room', id=None, slots=[], session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a', custom_data=None, asr_tokens=[[AsrToken(value="what's", confidence=1.0, range_start=0, range_end=6, time=None), AsrToken(value='the', confidence=1.0, range_start=7, range_end=10, time=None), AsrToken(value='date', confidence=1.0, range_start=11, range_end=15, time=None)]], asr_confidence=None, raw_input="what's the date", wakeword_id='bumblebee', lang=None)
[DEBUG:2020-10-04 16:34:43,664] rhasspydialogue_hermes: Recognized NluIntent(input="what's the date", intent=Intent(intent_name='Date', confidence_score=1.0), site_id='living-room', id=None, slots=[], session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a', custom_data=None, asr_tokens=[[AsrToken(value="what's", confidence=1.0, range_start=0, range_end=6, time=None), AsrToken(value='the', confidence=1.0, range_start=7, range_end=10, time=None), AsrToken(value='date', confidence=1.0, range_start=11, range_end=15, time=None)]], asr_confidence=None, raw_input="what's the date", wakeword_id='bumblebee', lang=None)
[ERROR:2020-10-04 16:35:11,421] rhasspydialogue_hermes: Session timed out for site living-room: living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a
[DEBUG:2020-10-04 16:35:11,422] rhasspydialogue_hermes: -> AsrStopListening(site_id='living-room', session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a')
[DEBUG:2020-10-04 16:35:11,422] rhasspydialogue_hermes: Publishing 100 bytes(s) to hermes/asr/stopListening
[DEBUG:2020-10-04 16:35:11,424] rhasspydialogue_hermes: -> DialogueSessionEnded(termination=DialogueSessionTermination(reason=<DialogueSessionTerminationReason.TIMEOUT: 'timeout'>), session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a', site_id='living-room', custom_data='bumblebee')
[DEBUG:2020-10-04 16:35:11,425] rhasspydialogue_hermes: Publishing 165 bytes(s) to hermes/dialogueManager/sessionEnded
[DEBUG:2020-10-04 16:35:11,432] rhasspyasr_kaldi_hermes: <- AsrStopListening(site_id='living-room', session_id='living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a')
[DEBUG:2020-10-04 16:35:11,432] rhasspyasr_kaldi_hermes: Stopping listening (session_id=living-room-bumblebee-44843948-f1a8-4255-ac9a-e8ab4d78ca5a)
[DEBUG:2020-10-04 16:35:11,438] rhasspydialogue_hermes: -> HotwordToggleOn(site_id='living-room', reason=<HotwordToggleReason.DIALOGUE_SESSION: 'dialogueSession'>)
[DEBUG:2020-10-04 16:35:11,440] rhasspydialogue_hermes: Publishing 54 bytes(s) to hermes/hotword/toggleOn
```

**Comment by synesthesiam** [comment]
I've added more graceful handling of missing site ids in https://github.com/rhasspy/rhasspy-dialogue-hermes/commit/5fb100d00ba76ca2f2a4d4eea1bf2a5dd0813b0b

This still doesn't explain why your satellite is sending the wrote site id though...

**Comment by DeadEnded** [comment]
I upgraded to 2.5.6 and am having issues with site_id as well.
```
[WARNING:2020-10-12 09:54:52,698] rhasspydialogue_hermes: No session for site default. Dropping recognition.
```
I don't use satellites at all - single server with a USB speakerphone attached.
I don't have any site ID's setup - so it should only be using the default.
Somehow it isn't creating the session... I haven't had time to do any digging to figure out why.

BTW I am getting this when I try to use the GUI to do an intent recognition with my custom handler.
Not sure how relevant that is, but wanted to make sure you had the correct information.

Thanks,
DeadEnd

**Comment by hawkeye217** [comment]
Upgraded to 2.5.7 a few minutes ago and now I see a warning in the logs on the master when triggering from a satellite.  Nothing works now - no voice or intent recognition and no TTS feedback.  

```
[DEBUG:2020-10-17 02:21:57,026] rhasspydialogue_hermes: <- HotwordDetected(model_id='computer_activate', model_version='', model_type='personal', current_sensitivity=0.54, site_id='musicpi4', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-10-17 02:21:57,026] rhasspydialogue_hermes: Playing WAV /usr/lib/rhasspy/etc/wav/beep_hi.wav
[DEBUG:2020-10-17 02:21:57,026] rhasspydialogue_hermes: -> HotwordToggleOff(site_id='musicpi4', reason=<HotwordToggleReason.PLAY_AUDIO: 'playAudio'>)
[DEBUG:2020-10-17 02:21:57,026] rhasspydialogue_hermes: Publishing 45 bytes(s) to hermes/hotword/toggleOff
[DEBUG:2020-10-17 02:21:57,027] rhasspydialogue_hermes: -> AsrToggleOff(site_id='musicpi4', reason=<AsrToggleReason.PLAY_AUDIO: 'playAudio'>)
[DEBUG:2020-10-17 02:21:57,027] rhasspydialogue_hermes: Publishing 45 bytes(s) to hermes/asr/toggleOff
[DEBUG:2020-10-17 02:21:57,027] rhasspydialogue_hermes: -> AudioPlayBytes(83948 byte(s)) to hermes/audioServer/musicpi4/playBytes/9fd4bafa-7a77-4879-bf3f-24ebd6d721a4
[DEBUG:2020-10-17 02:21:57,027] rhasspydialogue_hermes: Waiting for playFinished (timeout=1.2012925170068027)
[DEBUG:2020-10-17 02:21:57,028] rhasspyasr_kaldi_hermes: <- AsrToggleOff(site_id='musicpi4', reason=<AsrToggleReason.PLAY_AUDIO: 'playAudio'>)
[DEBUG:2020-10-17 02:21:57,029] rhasspyasr_kaldi_hermes: Disabled (AsrToggleReason.PLAY_AUDIO)
[DEBUG:2020-10-17 02:21:57,943] rhasspytts_cli_hermes: <- AudioPlayFinished(id='9fd4bafa-7a77-4879-bf3f-24ebd6d721a4', session_id='')
[DEBUG:2020-10-17 02:21:57,943] rhasspydialogue_hermes: <- AudioPlayFinished(id='9fd4bafa-7a77-4879-bf3f-24ebd6d721a4', session_id='')
[DEBUG:2020-10-17 02:21:57,944] rhasspydialogue_hermes: -> HotwordToggleOn(site_id='musicpi4', reason=<HotwordToggleReason.PLAY_AUDIO: 'playAudio'>)
[DEBUG:2020-10-17 02:21:57,944] rhasspydialogue_hermes: Publishing 45 bytes(s) to hermes/hotword/toggleOn
[DEBUG:2020-10-17 02:21:57,945] rhasspydialogue_hermes: -> AsrToggleOn(site_id='musicpi4', reason=<AsrToggleReason.PLAY_AUDIO: 'playAudio'>)
[DEBUG:2020-10-17 02:21:57,945] rhasspydialogue_hermes: Publishing 45 bytes(s) to hermes/asr/toggleOn
[WARNING:2020-10-17 02:21:57,946] rhasspydialogue_hermes: No session for id musicpi4-computer_activate-f1b73cbe-be2e-41cc-968f-5f0c75048de8
[DEBUG:2020-10-17 02:21:57,947] rhasspyasr_kaldi_hermes: <- AsrToggleOn(site_id='musicpi4', reason=<AsrToggleReason.PLAY_AUDIO: 'playAudio'>)
[DEBUG:2020-10-17 02:21:57,947] rhasspyasr_kaldi_hermes: Enabled
```

I made no changes in ``profile.json`` from a working 2.5.1 setup.  Again, I'm using an external MQTT broker (mosquitto 1.6.4) with a master called "master" and a satellite called "musicpi4".  Dialogue management is set to "Rhasspy" on the master.  

Let me know if you need any more information!  Thanks @synesthesiam!

**Comment by hawkeye217** [comment]
Fyi: I just downgraded my master to 2.5.1 (while leaving my satellite at 2.5.7) and all functionality is restored.

**Comment by synesthesiam** [comment]
OK, thank you for the feedback @hawkeye217.  It looks like I need create a more comprehensive test suite for the dialogue manager.

**Comment by benedikt-bartscher** [comment]
Since 2.5.7 i can only recognize one Intent and then everything stops working until i restart rhasspy:

```[WARNING:2020-10-12 09:54:52,698] rhasspydialogue_hermes: No session for site default. Dropping recognition.```

**Comment by synesthesiam** [comment]
I've updated the Docker image with a fix for this. Please pull the latest and try again. Debian packages are coming soon.

**Comment by hawkeye217** [comment]
Latest Docker image is working great now. Thanks @synesthesiam!
