### ISSUE TITLE
Cannot train in any version (2.5.4 - 2.5.7)

### ISSUE THREAD

**Issue by DeadEnded** [rhasspy/rhasspy#128]
Earlier today I was attempting to update to 2.5.7.
After the update training didn't seem to work (hanging) so I rolled back... to every version back to 2.5.4.
All of them now hang training... I waited and got this in the logs:
```
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1651, in api_text_to_speech
    results = await asyncio.gather(*aws)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1637, in speak
    session_id=session_id,
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 587, in speak_sentence
    handle_finished(), messages, message_types
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 959, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
I deleted everything in `profiles/en` except `profile.json`, `sentences.ini`, `kaldi_custom_words.txt` and then my custom files.  Started Rhasspy up again (tried 2.5.4 and 2.5.7) and still not working...

Not sure what I broke... but can someone give me some things to check/test to see if I can get this working again?

Thanks!
DeadEnd

**Comment by h4de5** [comment]
Too many sentences maybe? Try to remove half of it and check again. If that works you may need to find a other way to train kaldi. It ahould be possible to start the training from the command line

**Comment by DeadEnded** [comment]
I should have closed this... apologies... I can't remember what exactly fixed it - but I think I recreated everything and eventually got it straightened out.
