### ISSUE TITLE
cannot download Kaldi Profile

### ISSUE THREAD

**Issue by gplaza** [rhasspy/rhasspy#13]
Here the error : 

```
[ERROR:2020-03-23 23:27:36,879] rhasspyserver_hermes: NluError(error='Cannot connect to host localhost:5005 ssl:<ssl.SSLContext object at 0x7f8b99fb43a8> [Cannot assign requested address]', context='23d1c8f7-08c0-4e62-ad1a-1ff322173f66', siteId='default', sessionId='23d1c8f7-08c0-4e62-ad1a-1ff322173f66')

 [ERROR:2020-03-23 23:27:36,879] rhasspyserver_hermes: Cannot connect to host localhost:5005 ssl:<ssl.SSLContext object at 0x7f8b99fb43a8> [Cannot assign requested address]

 Traceback (most recent call last):

   File "/usr/lib/rhasspy-voltron/.venv/lib/python3.6/site-packages/quart/app.py", line 1471, in full_dispatch_request
 
     result = await self.dispatch_request(request_context)
 
   File "/usr/lib/rhasspy-voltron/.venv/lib/python3.6/site-packages/quart/app.py", line 1519, in dispatch_request
 
 
     return await handler(**request_.view_args)
 
 
   File "/usr/lib/rhasspy-voltron/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1145, in api_train
 
     result = await core.train()
 
   File "/usr/lib/rhasspy-voltron/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 391, in train
     raise TrainingFailedException(reason=nlu_response.error)

  rhasspyserver_hermes.TrainingFailedException: Cannot connect to host localhost:5005 ssl:<ssl.SSLContext object at 0x7f8b99fb43a8> [Cannot assign requested address]
```

**Comment by synesthesiam** [comment]
Do you have Rasa NLU set as your intent recognizer? It looks like it can't contact the Rasa server at localhost:5005

**Comment by gplaza** [comment]
indeed. yes.

Le lun. 23 mars 2020 à 23:12, Michael Hansen <notifications@github.com> a
écrit :

**Comment by gplaza** [comment]
Maybe there are some bubu in the save setting ... i have timeout error some time, but if i stop docker and recreate it ... it work.
