### ISSUE TITLE
Websocket Error

### ISSUE THREAD

**Issue by raufis27** [rhasspy/rhasspy#14]
As soon as I add websocket connection from NodeRed I get this: 

[ERROR:2020-03-27 23:58:34,434] rhasspyserver_hermes: BadRequest(400)
Traceback (most recent call last):
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.7/site-packages/quart/app.py", line 1940, in full_dispatch_websocket
    result = await self.preprocess_websocket(websocket_context)
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.7/site-packages/quart/app.py", line 1968, in preprocess_websocket
    result = await function()
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.7/site-packages/quart_cors/__init__.py", line 297, in _apply_websocket_cors
    abort(400)
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.7/site-packages/quart/exceptions.py", line 199, in abort
    raise error
quart.exceptions.BadRequest: BadRequest(400)
[ERROR:2020-03-27 23:58:31,429] rhasspyserver_hermes: BadRequest(400)
Traceback (most recent call last):
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.7/site-packages/quart/app.py", line 1940, in full_dispatch_websocket
    result = await self.preprocess_websocket(websocket_context)
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.7/site-packages/quart/app.py", line 1968, in preprocess_websocket
    result = await function()
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.7/site-packages/quart_cors/__init__.py", line 297, in _apply_websocket_cors
    abort(400)

**Comment by synesthesiam** [comment]
Should be fixed in latest version. Quart has decided for some reason that the HTTP Origin header is required now for websockets, which is against spec. Node-RED does not send this header, so a patch was required on the Rhasspy side to disable websocket origin checks.
