### ISSUE TITLE
Missing download details for cmusphinx-nl-5.2.tar.gz | Home Assistant base station

### ISSUE THREAD

**Issue by TheGroundZero** [rhasspy/rhasspy#159]
Hi all

I recently did my first install of Rhasspy.
I went for the base-sattelites model, where the base is my Home Assistant server with the Rhasspy add-on and the satellite is a Rpi 3B+

When training my model on the base station, I see in the logs the following output (it doesn't block the training):

```log
[ERROR:2021-01-05 08:09:08,884] rhasspyserver_hermes: Missing download details for cmusphinx-nl-5.2.tar.gz:cmusphinx-nl-5.2/etc/voxforge_nl_sphinx.dic
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 594, in api_profiles
    missing_files = rhasspyprofile.get_missing_files(core.profile)
  File "/usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/download.py", line 207, in get_missing_files
    assert file_details, f"Missing download details for {file_value}"
AssertionError: Missing download details for cmusphinx-nl-5.2.tar.gz:cmusphinx-nl-5.2/etc/voxforge_nl_sphinx.dic
```

I found a [post](https://community.home-assistant.io/t/rhasspy-offline-voice-assistant-toolkit/60862/3) on the community forum discussing these files and I downloaded the [Dutch compressed file](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Dutch/cmusphinx-nl-5.2.tar.gz/download).

I suppose I need to upload this file somewhere on my HA server, but I don't know where?
Or do I need to fix a reference in some file? Which file?

**Comment by synesthesiam** [comment]
Is this from Rhasspy 2.4? Please try using Rhasspy 2.5, as 2.4 is no longer supported.

I'd recommend using the Dutch profile with Kaldi instead of Pocketsphinx as well.

**Comment by TheGroundZero** [comment]
> Is this from Rhasspy 2.4? Please try using Rhasspy 2.5, as 2.4 is no longer supported.

Both client (RPi) and base (Home Assistant) are running 2.5.8

> I'd recommend using the Dutch profile with Kaldi instead of Pocketsphinx as well.

Changed to Kaldi - ARPA, getting similar error now

```log
[ERROR:2021-01-13 11:17:17,070] rhasspyserver_hermes: Missing download details for nl_kaldi-cgn.tar.gz:kaldi
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 594, in api_profiles
    missing_files = rhasspyprofile.get_missing_files(core.profile)
  File "/usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/download.py", line 207, in get_missing_files
    assert file_details, f"Missing download details for {file_value}"
AssertionError: Missing download details for nl_kaldi-cgn.tar.gz:kaldi
```

Training also fails

```log
TrainingFailedException: Command '['bash', '/usr/lib/rhasspy/.venv/lib/kaldi/egs/wsj/s5/utils/prepare_lang.sh', '/share/rhasspy/profiles/nl/kaldi/model/data/local/dict', '<unk>', '/share/rhasspy/profiles/nl/kaldi/model/data/local/lang', '/share/rhasspy/profiles/nl/kaldi/model/data/lang']' returned non-zero exit status 1.
```

```log
[ERROR:2021-01-13 11:18:24,400] rhasspyserver_hermes: Command '['bash', '/usr/lib/rhasspy/.venv/lib/kaldi/egs/wsj/s5/utils/prepare_lang.sh', '/share/rhasspy/profiles/nl/kaldi/model/data/local/dict', '<unk>', '/share/rhasspy/profiles/nl/kaldi/model/data/local/lang', '/share/rhasspy/profiles/nl/kaldi/model/data/lang']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1282, in api_train
    result = await core.train()
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 471, in train
    raise TrainingFailedException(reason=asr_response.error)
rhasspyserver_hermes.TrainingFailedException: Command '['bash', '/usr/lib/rhasspy/.venv/lib/kaldi/egs/wsj/s5/utils/prepare_lang.sh', '/share/rhasspy/profiles/nl/kaldi/model/data/local/dict', '<unk>', '/share/rhasspy/profiles/nl/kaldi/model/data/local/lang', '/share/rhasspy/profiles/nl/kaldi/model/data/lang']' returned non-zero exit status 1.
[ERROR:2021-01-13 11:18:24,399] rhasspyserver_hermes: AsrError(error="Command '['bash', '/usr/lib/rhasspy/.venv/lib/kaldi/egs/wsj/s5/utils/prepare_lang.sh', '/share/rhasspy/profiles/nl/kaldi/model/data/local/dict', '<unk>', '/share/rhasspy/profiles/nl/kaldi/model/data/local/lang', '/share/rhasspy/profiles/nl/kaldi/model/data/lang']' returned non-zero exit status 1.", site_id='master', context=None, session_id='ef7e42e2-ccd0-46ea-81f4-9794710f4327')
[DEBUG:2021-01-13 11:18:24,397] rhasspyserver_hermes: Handling AsrError (topic=hermes/error/asr, id=763cbd6c-1ee8-4557-93bb-b419f1e8333c)
[DEBUG:2021-01-13 11:18:21,347] rhasspyserver_hermes: Handling NluTrainSuccess (topic=rhasspy/nlu/master/trainSuccess, id=763cbd6c-1ee8-4557-93bb-b419f1e8333c)
[DEBUG:2021-01-13 11:18:21,040] rhasspyserver_hermes: Publishing 6116 bytes(s) to rhasspy/nlu/master/train
[DEBUG:2021-01-13 11:18:21,039] rhasspyserver_hermes: -> NluTrain
[DEBUG:2021-01-13 11:18:21,035] rhasspyserver_hermes: Publishing 6116 bytes(s) to rhasspy/asr/master/train
[DEBUG:2021-01-13 11:18:21,034] rhasspyserver_hermes: -> AsrTrain
```

**Comment by synesthesiam** [comment]
Please try again with 2.5.9 and re-open issue if the problem persists :+1:
