### ISSUE TITLE
Missing 2 required positional arguments: 'confidence' and 'raw_value'

### ISSUE THREAD

**Issue by raufis27** [rhasspy/rhasspy#16]
Installed latest version:
Ideas ? 
`
[ERROR:2020-04-02 16:25:57,676] rhasspyserver_hermes: on_message
Traceback (most recent call last):
  File "/usr/lib/rhasspy-voltron/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 910, in on_message
    topic, payload, self.subscribed_types
  File "/usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/client.py", line 259, in parse_mqtt_message
    message = message_type.from_dict(json_payload)
  File "/usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/nlu.py", line 92, in from_dict
    message.slots = [Slot.from_dict(s) for s in slot_dicts]
  File "/usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/nlu.py", line 92, in <listcomp>
    message.slots = [Slot.from_dict(s) for s in slot_dicts]
  File "/usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/intent.py", line 82, in from_dict
    slot = Slot(**object_dict)
TypeError: __init__() missing 2 required positional arguments: 'confidence' and 'raw_value'
[ERROR:2020-04-02 16:25:57,606] rhasspyserver_hermes: on_message
Traceback (most recent call last):
  File "/usr/lib/rhasspy-voltron/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 910, in on_message
    topic, payload, self.subscribed_types
  File "/usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/client.py", line 259, in parse_mqtt_message
    message = message_type.from_dict(json_payload)
  File "/usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/nlu.py", line 92, in from_dict
    message.slots = [Slot.from_dict(s) for s in slot_dicts]
  File "/usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/nlu.py", line 92, in <listcomp>
    message.slots = [Slot.from_dict(s) for s in slot_dicts]
  File "/usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/intent.py", line 82, in from_dict
    slot = Slot(**object_dict)
TypeError: __init__() missing 2 required positional arguments: 'confidence' and 'raw_value' 
`

**Comment by synesthesiam** [comment]
Can you describe your config a bit more? Are you using Docker or virtual environment?

I'm hoping this will be fixed by the end of the day either way.

**Comment by raufis27** [comment]
I am using docker version. At the moment I am running latest stable with Snips environment and testing 2.4 version. This problem related to 2.4, because previous version works ok. Here is my config :

`{
    "command": {
        "system": "hermes"
    },
    "dialogue": {
        "system": "hermes"
    },
    "intent": {
        "fsticuffs": {
            "fuzzy": false
        },
        "system": "fsticuffs"
    },
    "microphone": {
        "system": "hermes"
    },
    "mqtt": {
        "enabled": true,
        "host": "10.10.10.10",
        "publish_intents": false,
        "site_id": "basement"
    },
    "sounds": {
        "system": "hermes"
    },
    "speech_to_text": {
        "system": "kaldi"
    },
    "wake": {
        "system": "hermes"
    },
    "rhasspy": {
        "listen_on_start": false
    }
}`
Thank you.
