### ISSUE TITLE
Some missing file exceptions using the tts api

### ISSUE THREAD

**Issue by Daenara** [rhasspy/rhasspy#160]
Evening,

I was playing around with the Text to Speech API and encountered two exceptions. I was using the API test GUI that opens when you click on the version number. TTS still works, but I don't think the exceptions are intended so I am reporting them. Rhasspy version was 2.5.8 docker, just updated today from 2.5.8 docker, so obviously something changed. I have no idea since when those exceptions happen, never tried using the tts api before today.

Daenara

```
[ERROR:2021-01-06 18:41:42,902] rhasspyserver_hermes: NotFound(404)
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/static.py", line 129, in safe_join
    full_path = file_path_to_path(directory, *paths).resolve(strict=True)
  File "/usr/lib/python3.7/pathlib.py", line 1151, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "/usr/lib/python3.7/pathlib.py", line 355, in resolve
    return _resolve(base, str(path)) or sep
  File "/usr/lib/python3.7/pathlib.py", line 339, in _resolve
    target = accessor.readlink(newpath)
  File "/usr/lib/python3.7/pathlib.py", line 437, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/swagger_ui/static/text-to-speech'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/static.py", line 88, in send_static_file
    return await send_from_directory(self.static_folder, filename)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/static.py", line 161, in send_from_directory
    file_path = safe_join(directory, file_name)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/static.py", line 131, in safe_join
    raise NotFound()
quart.exceptions.NotFound: NotFound(404)
[DEBUG:2021-01-06 18:41:42,831] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=103b6f7a-983e-4f57-afa9-1fd502decbf5)
[DEBUG:2021-01-06 18:41:42,165] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/pi-hime/playBytes/a3279259-1cb1-4dcb-b579-28aa2e4c9887, id=103b6f7a-983e-4f57-afa9-1fd502decbf5)
[DEBUG:2021-01-06 18:41:42,073] rhasspyserver_hermes: Publishing 129 bytes(s) to hermes/tts/say
[DEBUG:2021-01-06 18:41:42,072] rhasspyserver_hermes: -> TtsSay(text='test', site_id='pi-hime', lang=None, id='a3279259-1cb1-4dcb-b579-28aa2e4c9887', session_id='', volume=1.0)
```

**Comment by synesthesiam** [comment]
Thanks for the report. I think there's been a change in how the `swagger-ui-py` package operates, and it makes the `/api/` not work correctly anymore.

For 2.5.9, I'll be moving the OpenAPI test page over to `/openapi/` to avoid this conflict.
