### ISSUE TITLE
missing dependencies in Docker File

### ISSUE THREAD

**Issue by volker67** [rhasspy/rhasspy#177]
when i try to use the command rhasspy-speakers-cli-hermes -h inside the docker container i got an error

_usr/lib/rhasspy/rhasspy-speakers-cli-hermes/bin/rhasspy-speakers-cli-hermes -h
Traceback (most recent call last):
File “/usr/lib/python3.7/runpy.py”, line 183, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File “/usr/lib/python3.7/runpy.py”, line 142, in _get_module_details
return _get_module_details(pkg_main_name, error)
File “/usr/lib/python3.7/runpy.py”, line 109, in _get_module_details
import(pkg_name)
File “/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/init.py”, line 11, in
import wavchunk
ModuleNotFoundError: No module named ‘wavchunk’_

i found out that the modules "wheel wavchunk and rhasspy-hermes" are not installed
fixed that with

_pip3 install wheel
pip3 install wavchunk
pip3 install rhasspy-hermes_

now works as expected

root@voice05:/# /usr/lib/rhasspy/rhasspy-speakers-cli-hermes/bin/rhasspy-speakers-cli-hermes -h
usage: rhasspy-speakers-cli-hermes [-h] --play-command PLAY_COMMAND
[–list-command LIST_COMMAND]
[–volume VOLUME] [–host HOST]
[–port PORT] [–username USERNAME]
[–password PASSWORD] [–tls]
[–tls-ca-certs TLS_CA_CERTS]
[–tls-certfile TLS_CERTFILE]
[–tls-keyfile TLS_KEYFILE]
[–tls-cert-reqs {CERT_REQUIRED,CERT_OPTIONAL,CERT_NONE}]
[–tls-version TLS_VERSION]
[–tls-ciphers TLS_CIPHERS]
[–site-id SITE_ID] [–debug]
[–log-format LOG_FORMAT]

optional arguments:
-h, --help show this help message and exit
–play-command PLAY_COMMAND
Command to play WAV data from stdin
–list-command LIST_COMMAND
Command to list available output devices
–volume VOLUME Volume scale to apply to all audio
–host HOST MQTT host (default: localhost)
–port PORT MQTT port (default: 1883)
–username USERNAME MQTT username
–password PASSWORD MQTT password
–tls Enable MQTT TLS
–tls-ca-certs TLS_CA_CERTS
MQTT TLS Certificate Authority certificate files
–tls-certfile TLS_CERTFILE
MQTT TLS client certificate file (PEM)
–tls-keyfile TLS_KEYFILE
MQTT TLS client key file (PEM)
–tls-cert-reqs {CERT_REQUIRED,CERT_OPTIONAL,CERT_NONE}
MQTT TLS certificate requirements for broker (default:
CERT_REQUIRED)
–tls-version TLS_VERSION
MQTT TLS version (default: highest)
–tls-ciphers TLS_CIPHERS
MQTT TLS ciphers to use
–site-id SITE_ID Hermes site id(s) to listen for (default: all)
–debug Print DEBUG messages to the console
–log-format LOG_FORMAT
Python logger format
root@voice05:/#

that happend with satellie on raspian docker image 2.5.8/9 and also with the latest x86 docker image 2.5.9 on my master

**Comment by zsawyer** [comment]
confirmed 

```
pi@raspberrypi:~ $ docker exec -i rhasspy /usr/lib/rhasspy/rhasspy-speakers-cli-hermes/bin/rhasspy-speakers-cli-hermes -h
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 11, in <module>
    import wavchunk
ModuleNotFoundError: No module named 'wavchunk'



pi@raspberrypi:~ $ docker exec -i rhasspy /usr/lib/rhasspy/rhasspy-speakers-cli-hermes/bin/rhasspy-speakers-cli-hermes -h
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 11, in <module>
    import wavchunk
ModuleNotFoundError: No module named 'wavchunk'
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ docker exec ^C
pi@raspberrypi:~ $ docker exec -i rhasspy pip3 install wheel
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.36.2
pi@raspberrypi:~ $ docker exec -i rhasspy pip3 install wavchunk
Collecting wavchunk
  Downloading https://files.pythonhosted.org/packages/0c/ab/8cae43190606eb0c0e319e5949c4da83336f8ce2dc53cfd3ccec258e827b/wavchunk-1.0.1.tar.gz
Building wheels for collected packages: wavchunk
  Running setup.py bdist_wheel for wavchunk: started
  Running setup.py bdist_wheel for wavchunk: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/df/3d/ab/c6a7f937eaa83e549c5d916fb702689cb82336bcc3f46d340a
Successfully built wavchunk
Installing collected packages: wavchunk
Successfully installed wavchunk-1.0.1
pi@raspberrypi:~ $ docker exec rhasspy pip3 install rhasspy-hermes
Collecting rhasspy-hermes
  Downloading https://files.pythonhosted.org/packages/8d/ac/14c762bfc75f34054b8394028184b3c87640cd0fa3ceeccaeef6f16f3fa8/rhasspy-hermes-0.6.0.tar.gz
Collecting dataclasses-json==0.4.2 (from rhasspy-hermes)
  Downloading https://files.pythonhosted.org/packages/84/a2/d33e29e37146f6a8a18a0975e13c6acb9439d6a8698d406ca8a5c736f302/dataclasses_json-0.4.2-py3-none-any.whl
Collecting paho-mqtt==1.5.0 (from rhasspy-hermes)
  Downloading https://files.pythonhosted.org/packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz (99kB)
Collecting marshmallow-enum<2.0.0,>=1.5.1 (from dataclasses-json==0.4.2->rhasspy-hermes)
  Downloading https://files.pythonhosted.org/packages/c6/59/ef3a3dc499be447098d4a89399beb869f813fee1b5a57d5d79dee2c1bf51/marshmallow_enum-1.5.1-py2.py3-none-any.whl
Collecting stringcase<2.0.0,==1.2.0 (from dataclasses-json==0.4.2->rhasspy-hermes)
  Downloading https://files.pythonhosted.org/packages/f3/1f/1241aa3d66e8dc1612427b17885f5fcd9c9ee3079fc0d28e9a3aeeb36fa3/stringcase-1.2.0.tar.gz
Collecting typing-inspect>=0.4.0 (from dataclasses-json==0.4.2->rhasspy-hermes)
  Downloading https://files.pythonhosted.org/packages/42/1c/66402db44184904a2f14722d317a4da0b5c8c78acfc3faf74362566635c5/typing_inspect-0.6.0-py3-none-any.whl
Collecting marshmallow<4.0.0,>=3.3.0 (from dataclasses-json==0.4.2->rhasspy-hermes)
  Downloading https://files.pythonhosted.org/packages/eb/5c/d43fa372e77df6e9783a8e5f29c3cccf27b1f83f3b84d571a22a58509147/marshmallow-3.10.0-py2.py3-none-any.whl (46kB)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.4.0->dataclasses-json==0.4.2->rhasspy-hermes)
  Downloading https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl
Collecting typing-extensions>=3.7.4 (from typing-inspect>=0.4.0->dataclasses-json==0.4.2->rhasspy-hermes)
  Downloading https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Building wheels for collected packages: rhasspy-hermes, paho-mqtt, stringcase
  Running setup.py bdist_wheel for rhasspy-hermes: started
  Running setup.py bdist_wheel for rhasspy-hermes: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/2e/56/93/b48eb136f9c2da083c03c3143413b040428924e6e586cde8c7
  Running setup.py bdist_wheel for paho-mqtt: started
  Running setup.py bdist_wheel for paho-mqtt: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/02/94/6c/8474137cb7a5a3e001d70a22c8ff919caee69435376bccce79
  Running setup.py bdist_wheel for stringcase: started
  Running setup.py bdist_wheel for stringcase: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a0/16/a0/16e2c81dbd47503b5a35583dfabde5a93b4cf98dbf0033dad5
Successfully built rhasspy-hermes paho-mqtt stringcase
Installing collected packages: marshmallow, marshmallow-enum, stringcase, mypy-extensions, typing-extensions, typing-inspect, dataclasses-json, paho-mqtt, rhasspy-hermes
Successfully installed dataclasses-json-0.4.2 marshmallow-3.10.0 marshmallow-enum-1.5.1 mypy-extensions-0.4.3 paho-mqtt-1.5.0 rhasspy-hermes-0.6.0 stringcase-1.2.0 typing-extensions-3.7.4.3 typing-inspect-0.6.0
pi@raspberrypi:~ $ docker exec rhasspy /usr/lib/rhasspy/rhasspy-speakers-cli-hermes/bin/rhasspy-speakers-cli-hermes -h
usage: rhasspy-speakers-cli-hermes [-h] --play-command PLAY_COMMAND
                                   [--list-command LIST_COMMAND]
                                   [--volume VOLUME] [--host HOST]
                                   [--port PORT] [--username USERNAME]
                                   [--password PASSWORD] [--tls]
                                   [--tls-ca-certs TLS_CA_CERTS]
                                   [--tls-certfile TLS_CERTFILE]
                                   [--tls-keyfile TLS_KEYFILE]
                                   [--tls-cert-reqs {CERT_REQUIRED,CERT_OPTIONAL,CERT_NONE}]
                                   [--tls-version TLS_VERSION]
                                   [--tls-ciphers TLS_CIPHERS]
                                   [--site-id SITE_ID] [--debug]
                                   [--log-format LOG_FORMAT]

optional arguments:
  -h, --help            show this help message and exit
  --play-command PLAY_COMMAND
                        Command to play WAV data from stdin
  --list-command LIST_COMMAND
                        Command to list available output devices
  --volume VOLUME       Volume scale to apply to all audio
  --host HOST           MQTT host (default: localhost)
  --port PORT           MQTT port (default: 1883)
  --username USERNAME   MQTT username
  --password PASSWORD   MQTT password
  --tls                 Enable MQTT TLS
  --tls-ca-certs TLS_CA_CERTS
                        MQTT TLS Certificate Authority certificate files
  --tls-certfile TLS_CERTFILE
                        MQTT TLS client certificate file (PEM)
  --tls-keyfile TLS_KEYFILE
                        MQTT TLS client key file (PEM)
  --tls-cert-reqs {CERT_REQUIRED,CERT_OPTIONAL,CERT_NONE}
                        MQTT TLS certificate requirements for broker (default:
                        CERT_REQUIRED)
  --tls-version TLS_VERSION
                        MQTT TLS version (default: highest)
  --tls-ciphers TLS_CIPHERS
                        MQTT TLS ciphers to use
  --site-id SITE_ID     Hermes site id(s) to listen for (default: all)
  --debug               Print DEBUG messages to the console
  --log-format LOG_FORMAT
                        Python logger format

```


I

**Comment by zsawyer** [comment]
I think there might be more broken here.

I thought this could explain why I cannot get my audio playback to work using latest stable docker image (2.5.9) but after installing these I still don't get it to work. It will always use the hdmi as output for aplay and the bluetooth headset doesn't show. 
Using **Pulse** gives 
```
[DEBUG:2021-03-07 03:24:17,987] rhasspyspeakers_cli_hermes: ['aplay', '-q', '-t', 'wav', '-D', 'pulse']
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

aplay: main:828: audio open error: Connection refused
[ERROR:2021-03-07 03:24:18,072] rhasspyspeakers_cli_hermes: handle_play
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 80, in handle_play
    subprocess.run(self.play_command, input=wav_bytes, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['aplay', '-q', '-t', 'wav', '-D', 'pulse']' returned non-zero exit status 1.
```

Which I can imagine being a follow up issue of 
```
[DEBUG:2021-03-07 03:35:19,518] rhasspyserver_hermes: Starting core
[DEBUG:2021-03-07 03:35:19,531] rhasspyserver_hermes: Connecting to localhost:12183 (retries: 0/10)
[ERROR:2021-03-07 03:35:19,540] rhasspyserver_hermes: mqtt connect
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 289, in start
    self.client.connect(self.host, self.port)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
2021-03-07 03:35:19,581 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-03-07 03:35:19,588 INFO supervisord started with pid 174
[DEBUG:2021-03-07 03:35:20,559] rhasspyserver_hermes: Connecting to localhost:12183 (retries: 1/10)
[ERROR:2021-03-07 03:35:20,562] rhasspyserver_hermes: mqtt connect
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 289, in start
    self.client.connect(self.host, self.port)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
2021-03-07 03:35:20,596 INFO spawned: 'mqtt' with pid 587
```
I basically did a fresh install of Rapberry Pi OS on my 4B then installed docker and ran this 2.5.9 image. 
[here](https://gist.github.com/zsawyer/eb7fa11c1be851ea20623f47344f91c7/bb8e924b4c913f9780e17396884eee8b09dabe40) is what I did so far).

**Comment by Romkabouter** [comment]
Hi there,

Is this still an issue in 2.5.11?
