### ISSUE TITLE
Audio Output: Remote - Invalid start byte

### ISSUE THREAD

**Issue by TRad8** [rhasspy/rhasspy#197]
I am using Rhasspy for quite some time now in combination with HomeAssistant and I am quite happy with it.
I tried using a satelite only for audio output. The base system is a NUC, the satelite is a Pi 3. I get the following error, when the base system plays the WAV on the satelite via Remote HTTP:

`
[ERROR:2021-03-05 08:16:41,151] rhasspyserver_hermes: 'utf-8' codec can't decode byte 0x80 in position 24: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1129, in api_play_wav
    url_or_path = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 24: invalid start byte
`

On a sidenode concerning the data sent over the network: Would it be possible to use TTS and Audio directly on the same station? This might be a feature request, but for me it makes sense to rather send the words to the satelite and have it TTS + audio output on the same machine than have it TTS on another machine where it sends the audio in WAV form.

Keep up the good work ye all!

**Comment by synesthesiam** [comment]
Thanks! If you're POST-ing WAV audio to `/api/play-wav`, make sure to set `Content-Type` to `audio/wav`. This should be done automatically if you're using the "Remote HTTP" option for audio output.

> Would it be possible to use TTS and Audio directly on the same station?

If your NUC is the base and the Pi 3 is a satellite, it should be as easy as configuring the Pi 3 to use local TTS and audio output systems like NanoTTS and aplay. From your question above, I'm curious how you have your two machines configured.

**Comment by Romkabouter** [comment]
@TRad8 did you find answers to your question?

**Comment by redlegoman** [comment]
THis looks old, but it seems it is still open. I too have this problem. I am trying to send audio from one rhasspy install to another. The remote rhasspy works fine and plays audio as expected. If I point the local rhasspy to the remote HTTP of the remote it does not play and I see this in the log of the local rhasspy:
![image](https://user-images.githubusercontent.com/1895294/191701606-fb8446bb-55a4-4ed4-841b-60cfbe4dc42e.png)


```
[DEBUG:2022-09-22 09:42:55,083] rhasspyserver_hermes: TTS timeout will be 30 second(s)
[DEBUG:2022-09-22 09:42:55,084] rhasspyserver_hermes: -> TtsSay(text='bananas are the only fruit', site_id='default', lang=None, id='e4bec31a-5e0a-4a38-a377-b95f42ed02f5', session_id='', volume=1.0)
[DEBUG:2022-09-22 09:42:55,084] rhasspyserver_hermes: Publishing 151 bytes(s) to hermes/tts/say
[DEBUG:2022-09-22 09:42:55,086] rhasspytts_larynx_hermes: <- TtsSay(text='bananas are the only fruit', site_id='default', lang=None, id='e4bec31a-5e0a-4a38-a377-b95f42ed02f5', session_id='', volume=1.0)
[DEBUG:2022-09-22 09:42:55,086] rhasspytts_larynx_hermes: Using WAV from cache: /profiles/en/tts/larynx/cache/ee8626bff17b162f3f8d8bc84c6be71c.wav
[DEBUG:2022-09-22 09:42:55,086] rhasspytts_larynx_hermes: -> AudioPlayBytes(77868 byte(s)) to hermes/audioServer/default/playBytes/e4bec31a-5e0a-4a38-a377-b95f42ed02f5
[DEBUG:2022-09-22 09:42:55,086] rhasspytts_larynx_hermes: Waiting for play finished (timeout=2.0147165532879816)
[DEBUG:2022-09-22 09:42:55,088] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/default/playBytes/e4bec31a-5e0a-4a38-a377-b95f42ed02f5, id=ee3c5e8c-3e5e-4521-99d1-ee4d8f4fb2d0)
[DEBUG:2022-09-22 09:42:55,088] rhasspyspeakers_cli_hermes: <- AudioPlayBytes(77868 byte(s))
[DEBUG:2022-09-22 09:42:55,088] rhasspyspeakers_cli_hermes: ['curl', '-s', '-X', 'POST', '-H', 'Content-Type:', 'audio/wav', '--data-binary', '@-', 'http://raspberrypi.local:12101/api/play-wav']
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 29: invalid start byte[DEBUG:2022-09-22 09:42:55,275] rhasspyspeakers_cli_hermes: -> AudioPlayFinished(id='e4bec31a-5e0a-4a38-a377-b95f42ed02f5', session_id='e4bec31a-5e0a-4a38-a377-b95f42ed02f5')
[DEBUG:2022-09-22 09:42:55,275] rhasspyspeakers_cli_hermes: Publishing 99 bytes(s) to hermes/audioServer/default/playFinished
[DEBUG:2022-09-22 09:42:55,278] rhasspytts_larynx_hermes: <- AudioPlayFinished(id='e4bec31a-5e0a-4a38-a377-b95f42ed02f5', session_id='e4bec31a-5e0a-4a38-a377-b95f42ed02f5')
[DEBUG:2022-09-22 09:42:55,279] rhasspytts_larynx_hermes: -> TtsSayFinished(site_id='default', id='e4bec31a-5e0a-4a38-a377-b95f42ed02f5', session_id='')
[DEBUG:2022-09-22 09:42:55,279] rhasspytts_larynx_hermes: Publishing 84 bytes(s) to hermes/tts/sayFinished
[DEBUG:2022-09-22 09:42:55,281] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=ee3c5e8c-3e5e-4521-99d1-ee4d8f4fb2d0)
```

Doing it from the command line works ok:

```
# curl -X POST http://raspberrypi.local:12101/api/play-wav -H "Content-Type: audio/wav" --data-binary @"/docker/rhasspy/.config.saved/rhasspy/profiles/en/wav/beep_lo.wav"
OK
```
