### ISSUE TITLE
Google Wavenet TTS invalid Argument

### ISSUE THREAD

**Issue by coxtor** [rhasspy/rhasspy#200]
I am using Rhassüy 2.5.9 and just selected Google Wavenet for TTS. I have configured a correct credential file, however when testing I get this error:

```

[ERROR:2021-03-14 13:50:08,908] rhasspyserver_hermes: 400 Request contains an invalid argument.
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1700, in api_text_to_speech
    results = await asyncio.gather(*aws)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1686, in speak
    volume=volume,
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 608, in speak_sentence
    raise TtsException(say_response.error)
rhasspyserver_hermes.TtsException: 400 Request contains an invalid argument.
[ERROR:2021-03-14 13:50:08,907] rhasspyserver_hermes: TtsError(error='400 Request contains an invalid argument.', site_id='base', context='0bee55c0-9051-48c1-8d4e-b2b3576fadd3', session_id='')
[DEBUG:2021-03-14 13:50:08,905] rhasspyserver_hermes: Handling TtsError (topic=hermes/error/tts, id=1c50ec45-c79d-4ac8-b2de-68fd44bce610)
[DEBUG:2021-03-14 13:50:06,556] rhasspyserver_hermes: Publishing 143 bytes(s) to hermes/tts/say
[DEBUG:2021-03-14 13:50:06,556] rhasspyserver_hermes: -> TtsSay(text='Setze Szene gemütlich', site_id='base', lang=None, id='0bee55c0-9051-48c1-8d4e-b2b3576fadd3', session_id='', volume=1.0)
```

**Comment by Chreece** [comment]
I'm far from an expert but could that umlaut by gemütlich and the lang=None be the problem?
Maybe you should set lang=de.
Just guessing / trying to help

**Comment by coxtor** [comment]
Uff I missed that - thank you - my bad!
