### ISSUE TITLE
[Audio Output] refreshing available devices -> Not a request for input devices

### ISSUE THREAD

**Issue by zsawyer** [rhasspy/rhasspy#202]
Hi, 
I have setup Rhasspy pretty OK I guess. The microphone is working, intents are being sent to HASS. 

# Issue

I am trying to test the speaker with Rhasspy and that doesn't work. 
The weird thing is that the error message mentions "input devices" when I would be expecting "output devices".

# Specs
## Rhasspy
rhasspy_2.5.9_armhf.deb

## Settings:
Audio Recording: pyaudio (Recommended)
Audio Playing: aplay (Recommended)

## Devices
- Raspberry Pi 4 Model B
- ReSpeaker 2-Mics Pi HAT (see [this gist](https://gist.github.com/zsawyer/effc378ade8d900c0016b5730cbd6be5) on how I installed the driver) 

# Debug Info
## aplay -l
```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 2: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 [bcm2835-i2s-wm8960-hifi wm8960-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

## Server-Log from Rhasppy:
Full log: [rhasspy_no-snd.log](https://github.com/rhasspy/rhasspy/files/6174591/rhasspy_no-snd.log)

### Speak "test" (on Home)
```
[DEBUG:2021-03-20 00:56:37,723] rhasspyserver_hermes: -> TtsSay(text='test', site_id='default', lang=None, id='b8a6c1bb-5d9f-4148-8e0f-16b86f775367', session_id='', volume=1.0)
[DEBUG:2021-03-20 00:56:37,724] rhasspyserver_hermes: Publishing 129 bytes(s) to hermes/tts/say
[DEBUG:2021-03-20 00:56:37,731] rhasspytts_cli_hermes: <- TtsSay(text='test', site_id='default', lang=None, id='b8a6c1bb-5d9f-4148-8e0f-16b86f775367', session_id='', volume=1.0)
[DEBUG:2021-03-20 00:56:37,753] rhasspytts_cli_hermes: ['nanotts', '-v', 'en-US', '-o', '/tmp/tmptqdmgfn5.wav']
Using Lingware directory: /usr/lib/rhasspy/lib/nanotts/pico/lang
read: 4 bytes from stdin
using lang: en-US
wrote "/tmp/tmptqdmgfn5.wav" (20524 bytes)
[DEBUG:2021-03-20 00:56:37,989] rhasspytts_cli_hermes: Got 20524 byte(s) of WAV data
[DEBUG:2021-03-20 00:56:37,998] rhasspytts_cli_hermes: -> AudioPlayBytes(20524 byte(s)) to hermes/audioServer/default/playBytes/b8a6c1bb-5d9f-4148-8e0f-16b86f775367
[DEBUG:2021-03-20 00:56:38,023] rhasspytts_cli_hermes: Waiting for play finished (timeout=0.89)
[DEBUG:2021-03-20 00:56:38,029] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/default/playBytes/b8a6c1bb-5d9f-4148-8e0f-16b86f775367, id=7715dfed-97a8-4b38-9265-c3d11f1fce5c)
[WARNING:2021-03-20 00:56:38,920] rhasspytts_cli_hermes: Did not receive playFinished before timeout
[DEBUG:2021-03-20 00:56:38,939] rhasspytts_cli_hermes: -> TtsSayFinished(site_id='default', id='b8a6c1bb-5d9f-4148-8e0f-16b86f775367', session_id='')
[DEBUG:2021-03-20 00:56:38,940] rhasspytts_cli_hermes: Publishing 84 bytes(s) to hermes/tts/sayFinished
[DEBUG:2021-03-20 00:56:38,963] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=7715dfed-97a8-4b38-9265-c3d11f1fce5c)
[DEBUG:2021-03-20 00:56:38,965] rhasspydialogue_hermes: <- TtsSayFinished(site_id='default', id='b8a6c1bb-5d9f-4148-8e0f-16b86f775367', session_id='')
```
### Refresh available devices (in Audio Playing settings)
```
[DEBUG:2021-03-20 00:37:44,495] rhasspyserver_hermes: -> AudioGetDevices(modes=[<AudioDeviceMode.OUTPUT: 'output'>], site_id='default', id='04b34d50-d2d2-411d-b26c-093e159c5e3a', test=False)
[DEBUG:2021-03-20 00:37:44,496] rhasspyserver_hermes: Publishing 103 bytes(s) to rhasspy/audioServer/getDevices
[DEBUG:2021-03-20 00:37:44,503] rhasspymicrophone_pyaudio_hermes: <- AudioGetDevices(modes=[<AudioDeviceMode.OUTPUT: 'output'>], site_id='default', id='04b34d50-d2d2-411d-b26c-093e159c5e3a', test=False)
[DEBUG:2021-03-20 00:37:44,503] rhasspymicrophone_pyaudio_hermes: Not a request for input devices
[ERROR:2021-03-20 00:38:14,519] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 810, in api_speakers
    speakers = await core.get_speakers()
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 858, in get_speakers
    handle_finished(), messages, message_types
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 971, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

Note: someone else also ran into this issue: https://community.rhasspy.org/t/dont-understand-how-to-be-heard-by-rhasspy/1447/40

**Comment by zsawyer** [comment]
appearently rebooting again fixed it
