### ISSUE TITLE
Hardware_Info list index out of range - Rock Pi S

### ISSUE THREAD

**Issue by kuumaur** [rhasspy/rhasspy#206]
Hi Guys,
I am getting this output, when I use Porcupine or Snowboy as wake word.
It seems, that the Hardware I am using is not safe identified.

Armbian Legacy (Armbian_21.02.3_Rockpi-s_buster_legacy_4.4.247)
Linux pi3 4.4.247-rockpis #1 SMP PREEMPT Mon Mar 8 08:35:13 UTC 2021 aarch64 GNU/Linux
root@pi3:~# lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               2
Model name:          Cortex-A35
Stepping:            r0p2
CPU max MHz:         1296.0000
CPU min MHz:         408.0000
BogoMIPS:            48.00
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
Flags:               fp asimd aes pmull sha1 sha2 crc32

(History: https://community.rhasspy.org/t/rock-pi-s-issues-with-wake-words/2548/3)

2021-04-01 19:13:13,185 INFO success: wake_word entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 15, in <module>
    import pvporcupine
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 13, in <module>
    from .util import *
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/util.py", line 54, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/util.py", line 47, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/util.py", line 23, in _pv_linux_machine
    hardware_info = [x for x in cpu_info.split('\n') if 'Hardware' in x][0]
IndexError: list index out of range
^C2021-04-01 19:13:18,275 WARN received SIGINT indicating exit request

**Comment by synesthesiam** [comment]
Hi @kuumaur, it would probably be worth opening an issue over on the [porcupine](https://github.com/Picovoice/porcupine) page about this. I'll keep this issue open in case someone has heard of a solution, but I hope we can avoid forking the pvporcupine package to fix any bugs :slightly_smiling_face:

**Comment by kuumaur** [comment]
https://github.com/Picovoice/porcupine/issues/389

**Comment by kuumaur** [comment]
Hi @synesthesiam,
the Issue is solved, for now
(https://github.com/Picovoice/porcupine/issues/394)
What are the next steps to test that?
Do you put the new release of Porcupine into 2.5.10?
or
How do I update my 2.5.9 with the new Porcupine version?

Br Kuu Maur
