### ISSUE TITLE
Audio Problems (Satellite / Base)

### ISSUE THREAD

**Issue by DustyArmstrong** [rhasspy/rhasspy#232]
I'm following the Tutorial (https://rhasspy.readthedocs.io/en/latest/tutorials/), specifically the section on "Test Microphone". I can select my microphone from the PyAudio menu, but when I test it, it just reverts to the "Default Device". 

I've tried multiple mics (all USB), with the same effect. My USB speaker does work, for reference. The microphones work with arecord, so that's a plus, just not PyAudio.

I also keep losing text-to-speech, as well as the recorded audio of the last command. The intent is still sent and subsequently recognized by the base server (timeout error is the reported problem). This is the same whether I run TTS on the satellite or on the base server. My USB speaker still beeps when woken. 

I'm running on a Raspberry Pi 3B+, as a remote site with a Hassio connected base station.

If it's of interest, the error log. It seemed to start after I was trying to get intent working with Hassio.

```[ERROR:2021-06-17 19:49:48,910] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1692, in api_text_to_speech
    results = await asyncio.gather(*aws)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1678, in speak
    say_chars_per_second=say_chars_per_second,
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 616, in speak_sentence
    handle_finished(), messages, message_types, timeout_seconds=timeout_seconds
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 994, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[DEBUG:2021-06-17 19:49:19,894] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=a1a5e538-8f49-4238-8ebd-3d4c62e2e672)
[DEBUG:2021-06-17 19:49:18,884] rhasspyserver_hermes: Publishing 122 bytes(s) to hermes/tts/say
[DEBUG:2021-06-17 19:49:18,882] rhasspyserver_hermes: -> TtsSay(text='test', site_id='', lang=None, id='43b482ab-f865-4e43-bf02-a09407128905', session_id='', volume=1.0)
[DEBUG:2021-06-17 19:49:18,877] rhasspyserver_hermes: Subscribed to hermes/error/audioServer/play
[DEBUG:2021-06-17 19:49:18,875] rhasspyserver_hermes: Subscribed to hermes/audioServer//playBytes/#
[DEBUG:2021-06-17 19:49:18,873] rhasspyserver_hermes: Subscribed to hermes/error/tts
[DEBUG:2021-06-17 19:49:18,872] rhasspyserver_hermes: Subscribed to hermes/tts/sayFinished
[DEBUG:2021-06-17 19:49:18,869] rhasspyserver_hermes: TTS timeout will be 30 second(s)```

**Comment by DustyArmstrong** [comment]
So I'm looking at my Hassio base station, and the logs suggest more timeouts.

```
[DEBUG:2021-06-17 21:59:02,322] rhasspyserver_hermes: TTS timeout will be 30 second(s)
[DEBUG:2021-06-17 21:59:02,322] rhasspyserver_hermes: -> TtsSay(text='this is a test', site_id='default', lang=None, id='6d007b7f-ddfd-480f-ab19-8dea61060ecf', session_id='', volume=1.0)
[DEBUG:2021-06-17 21:59:02,322] rhasspyserver_hermes: Publishing 139 bytes(s) to hermes/tts/say
[DEBUG:2021-06-17 21:59:02,365] rhasspytts_cli_hermes: <- TtsSay(text='this is a test', site_id='default', lang=None, id='6d007b7f-ddfd-480f-ab19-8dea61060ecf', session_id='', volume=1.0)
[DEBUG:2021-06-17 21:59:02,365] rhasspytts_cli_hermes: ['nanotts', '-v', 'en-US', '-o', '/tmp/tmphlmjb96q.wav']
Using Lingware directory: /usr/lib/rhasspy/.venv/lib/nanotts/pico/lang
read: 14 bytes from stdin
using lang: en-US
wrote "/tmp/tmphlmjb96q.wav" (35884 bytes)
[DEBUG:2021-06-17 21:59:02,387] rhasspytts_cli_hermes: Got 35884 byte(s) of WAV data
[DEBUG:2021-06-17 21:59:02,387] rhasspytts_cli_hermes: -> AudioPlayBytes(35884 byte(s)) to hermes/audioServer/default/playBytes/6d007b7f-ddfd-480f-ab19-8dea61060ecf
[DEBUG:2021-06-17 21:59:02,388] rhasspytts_cli_hermes: Waiting for play finished (timeout=1.37)
[DEBUG:2021-06-17 21:59:02,389] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/default/playBytes/6d007b7f-ddfd-480f-ab19-8dea61060ecf, id=59704492-de8f-4b3c-bbb6-ed32f2b30403)
[WARNING:2021-06-17 21:59:03,760] rhasspytts_cli_hermes: Did not receive playFinished before timeout
[DEBUG:2021-06-17 21:59:03,761] rhasspytts_cli_hermes: -> TtsSayFinished(site_id='default', id='6d007b7f-ddfd-480f-ab19-8dea61060ecf', session_id='')
[DEBUG:2021-06-17 21:59:03,761] rhasspytts_cli_hermes: Publishing 84 bytes(s) to hermes/tts/sayFinished
[DEBUG:2021-06-17 21:59:03,762] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=59704492-de8f-4b3c-bbb6-ed32f2b30403)
[DEBUG:2021-06-17 21:59:03,763] rhasspyserver_hermes: -> AudioToggleOn(site_id='default')
[DEBUG:2021-06-17 21:59:03,763] rhasspyserver_hermes: Publishing 21 bytes(s) to hermes/audioServer/toggleOn
```

**Comment by DustyArmstrong** [comment]
Issue resolved. 

When I was doing some other work, I had accidentally removed the site ID "default". The box is pre-populated with a slightly grayed out "default", which caused me to overlook it.
