### ISSUE TITLE
Timeout with base/satellite setup

### ISSUE THREAD

**Issue by TheZoker** [rhasspy/rhasspy#236]
I just tried to re-activate my base/satellite setup, but when sending an intent from the satellite to the base, I get an timeout error:

```
[WARNING:2021-07-23 02:27:18,532] rhasspyserver_hermes: Message queue missing (topic=hermes/error/nlu, id=c6c5b756-6a47-4531-9f02-a226f391341f)
[DEBUG:2021-07-23 02:27:18,530] rhasspyserver_hermes: Handling NluError (topic=hermes/error/nlu, id=c6c5b756-6a47-4531-9f02-a226f391341f)
[ERROR:2021-07-23 02:27:18,488] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1452, in api_text_to_intent
    site_id=site_id,
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 2706, in text_to_intent_dict
    text, intent_filter=intent_filter, site_id=site_id
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 524, in recognize_intent
    handle_intent(), messages, message_types
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 995, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[DEBUG:2021-07-23 02:26:48,457] rhasspyserver_hermes: Publishing 273 bytes(s) to hermes/nlu/query
[DEBUG:2021-07-23 02:26:48,456] rhasspyserver_hermes: -> NluQuery(input='Lautsprecher an', site_id='satellite', id='93bc81a6-1831-485b-8c94-913e302afcd8', intent_filter=None, session_id='93bc81a6-1831-485b-8c94-913e302afcd8', wakeword_id=None, lang=None, custom_data=None, asr_confidence=None, custom_entities=None)
```

Setting of the base (running on proxmox):

![image](https://user-images.githubusercontent.com/1368405/126727816-fdf9c54c-c610-4136-bbf0-b1b622934957.png)

```json
{
    "handle": {
        "system": "hass"
    },
    "home_assistant": {
        "access_token": "xxx",
        "url": "https://192.168.178.100:8123"
    },
    "intent": {
        "system": "fuzzywuzzy"
    },
    "mqtt": {
        "site_id": "base"
    },
    "speech_to_text": {
        "system": "kaldi"
    },
    "text_to_speech": {
        "system": "picotts"
    }
}
```

Setting of the satellite (running on a raspberry 3B):

![image](https://user-images.githubusercontent.com/1368405/126727802-a66591c5-1b5c-4c8b-8bc4-09b40f87e4ee.png)

```json
{
    "home_assistant": {
        "url": ""
    },
    "intent": {
        "remote": {
            "url": "http://192.168.178.82:12101/api/text-to-intent"
        },
        "system": "remote"
    },
    "microphone": {
        "pyaudio": {
            "device": "1"
        },
        "system": "pyaudio"
    },
    "mqtt": {
        "site_id": "satellite"
    },
    "sounds": {
        "aplay": {
            "device": "default:CARD=Headphones"
        },
        "system": "aplay"
    },
    "speech_to_text": {
        "remote": {
            "url": "http://192.168.178.82:12101/api/speech-to-text"
        },
        "system": "remote"
    },
    "text_to_speech": {
        "espeak": {
            "voice": "de"
        },
        "remote": {
            "url": "http://192.168.178.82:12101/api/text-to-speech"
        },
        "system": "remote"
    },
    "wake": {
        "pocketsphinx": {
            "keyphrase": "okay snips"
        },
        "porcupine": {
            "keyword_path": "computer.ppn"
        },
        "raven": {
            "keywords": {
                "default": {
                    "enabled": true
                }
            }
        },
        "snowboy": {
            "model": "Hey_computer.pmdl"
        },
        "system": "snowboy"
    }
}
```

When I ping the base from the satellite I get positive results:
```bash
pi@raspberrypi:~ $ ping 192.168.178.82 -p 12101
PATTERN: 0x121001
PING 192.168.178.82 (192.168.178.82) 56(84) bytes of data.
64 bytes from 192.168.178.82: icmp_seq=1 ttl=64 time=1.79 ms
64 bytes from 192.168.178.82: icmp_seq=2 ttl=64 time=1.72 ms
64 bytes from 192.168.178.82: icmp_seq=3 ttl=64 time=1.75 ms
64 bytes from 192.168.178.82: icmp_seq=4 ttl=64 time=2.15 ms
64 bytes from 192.168.178.82: icmp_seq=5 ttl=64 time=1.91 ms
64 bytes from 192.168.178.82: icmp_seq=6 ttl=64 time=1.41 ms
64 bytes from 192.168.178.82: icmp_seq=7 ttl=64 time=1.53 ms
--- 192.168.178.82 ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 15ms
rtt min/avg/max/mdev = 1.410/1.751/2.152/0.229 ms
```

Any idea why I get this timeout? How can I solve this? Thanks!

**Comment by drhirn** [comment]
Don't know, if this is related to your problem. But you have to define the satellites siteId in the base-configuration. See https://rhasspy.readthedocs.io/en/latest/tutorials/#shared-mqtt-broker

**Comment by TheZoker** [comment]
Hmm I don't use MQTT, so I'm not sure if this is the issue 🤔

**Comment by drhirn** [comment]
Ahhhh, sorry!

**Comment by TheZoker** [comment]
For anybody who also struggles with this issue:
@drhirn was right, you need to set the satellite siteIds for every remote action, even if it is not MQTT (maybe the docs should be updated to reflect this)
