### ISSUE TITLE
32 bit raspberry pi debian package installs 64 bit porcupine training?

### ISSUE THREAD

**Issue by cmsimike** [rhasspy/rhasspy#238]
Hi,

I am trying to get rhasspy setup on a raspberry pi (running OSMC) and I believe the wakeword bundled with the `rhasspy_2.5.10_armhf.deb` package is the 64 bit files?

```bash
[DEBUG:2021-07-27 18:56:23,230] rhasspywake_porcupine_hermes: Loading porcupine (kw=['/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi/porcupine_raspberry-pi.ppn'], kwdirs=['/home/osmc/.config/rhasspy/profiles/en/porcupine', '/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi'], sensitivity=[0.5])
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 260, in <module>
    main()
  File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 127, in main
    keyword_paths=[str(kw) for kw in args.keyword], sensitivities=sensitivities
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 68, in create
    sensitivities=sensitivities)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 60, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pvporcupine/lib/raspberry-pi/cortex-a72-aarch64/libpv_porcupine.so: wrong ELF class: ELFCLASS64
```

**Comment by ottobjorkland** [comment]
I have the same problem. I have tried both 32-bit and 64-bit OS on my Raspberry Pi, but the same error message occurs. Have you found any solution to this?
