### ISSUE TITLE
HTTP Post /api/play-wav error on destination

### ISSUE THREAD

**Issue by Chreece** [rhasspy/rhasspy#246]
On my RpiZero, the "source" (Satellite without speakers), I have the Audio Output to post to the HTTP point:
`http://<rpiIP>:<Port>/api/play-wav`
which is a Raspberry Pi, the "destination" (Satellite with speakers).
When I try to test the Speak from sources page I got on destination:
```
rhasspyserver_hermes: 'utf-8' codec can't decode byte 0xf0 in position 5: invalid continuation byte
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1121, in api_play_wav
    url_or_path = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 5: invalid continuation byte
```
TextToSpeech on source is HermesMQTT (my base station). Also tried Espeak on source but I got  the same logs on destination.

**Comment by h4de5** [comment]
have a look at #129
