### ISSUE TITLE
Raspberry Pi OS "Bullseye" base does not install libffi6 needed by rhasspy precompiled packages.

### ISSUE THREAD

**Issue by HeofHIShirts** [rhasspy/rhasspy#259]
Just set up rhasspy on an RPi3B+ with the full meal deal options using the Raspberry Pi OS based on Debian Bullseye (Debian 11).

Console was giving me many errors about not being able to find libffi.so.6 and the result was being unable to use or configure any wakeword systems as well as having an attempt to capture audio from my working microphone fail with a TimeoutError.

Bullseye-based systems install version 7 of libffi to their system. it appears, so there wasn't a file for rhasspy to find and use.

The solution to get the system running, once I realized what the problem was, was to 

`sudo apt-get install libffi6`

and then rhasspy worked perfectly with wakeword detection, finding the model files, and command processing.

In the next version/point upgrade, we may need to advance which version of libffi to look for, or make sure that libffi6 gets installed in the packaging manifest for the precompiled binaries. 

Thanks for making rhasspy, it's a really useful tool around our house for smart home controls without sending things out to large corporations to datamine with.

**Comment by EternityForest** [comment]
I think the issue is an old version of python packaged with Rhasspy, looking for a matching old version of libffi

**Comment by donburch888** [comment]
Just spent a couple of days trying to install Rhasspy on a satellite (RasPi Zero, reSpeaker 2-mic HAT), following the tutorial I am developing... 
Installed https://github.com/Hintak/seeed-voicecard.git (which takes ages and looks as though it is changing to an old kernel).  arecord and aplay tested OK. 
Installed rhasspy_armel.deb and run... 
Enabled External MQTT, save and restart OK.
Enabled arecord, save and restart.
THIS is where it falls down

```[DEBUG:2022-01-07 12:30:45,294] rhasspymicrophone_cli_hermes: Connected to MQTT broker
[DEBUG:2022-01-07 12:30:45,304] rhasspymicrophone_cli_hermes: Subscribed to rhasspy/audioServer/getDevices
[DEBUG:2022-01-07 12:30:45,316] rhasspymicrophone_cli_hermes: Subscribed to hermes/audioServer/toggleSummaryOff
[DEBUG:2022-01-07 12:30:45,337] rhasspymicrophone_cli_hermes: Subscribed to hermes/audioServer/toggleSummaryOn
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 13, in <module>
    import soundfile
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/soundfile.py", line 16, in <module>
    from ctypes.util import find_library as _find_library
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
2022-01-07 12:30:48,365 INFO exited: speakers (exit status 1; not expected)
2022-01-07 12:30:49,405 INFO spawned: 'speakers' with pid 1633
2022-01-07 12:30:50,434 INFO success: speakers entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 13, in <module>
    import soundfile
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/soundfile.py", line 16, in <module>
    from ctypes.util import find_library as _find_library
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
2022-01-07 12:31:04,396 INFO exited: speakers (exit status 1; not expected)
```
Thanks Alex for the fix !

I used RasPi Imager and the Debian (non-docker) install, so it would have picked up the latest version of Raspberry Pi OS Lite - a trick for inexperienced players :-(  

I don't want to start off putting temporary workarounds in my tutorial; so guess I'll just have to put my tutorial on hold until this is fixed.

**Comment by donburch888** [comment]
Just done a fresh Rhasspy (debian, non-docker) install on a fresh, new, updated Raspberry Pi OS 32-bit 04-04-2022 install. 

libffi.so.6 did not get installed ... so **this issue is still current**; albeit easily fixed for people who find this issue.

**Comment by robertmielewczyk** [comment]
On raspi 3 (arm64) with Debian 11 it may be not possible to simply run
```bash
sudo apt-get install libffi6 # not found
```
if above command failed. You can add repo from a previous Debian 10 to your sources for apt:
```bash
sudo nano /etc/apt/sources.list

# Add these lines should be in your sources
deb http://deb.debian.org/debian bullseye main contrib non-free # Debian 11 repo
deb http://deb.debian.org/debian buster main contrib non-free   # Debian 10 repo (add this)
# ... Other packages bellow
```

**install rhasspy dependencies**
```bash
sudo apt install libffi6      # works
sudo apt install libgfortran4 # works (rhasspy dependency)
```

**Comment by nwithan8** [comment]
> On raspi 3 (arm64) with Debian 11 it may be not possible to simply run
> 
> ```shell
> sudo apt-get install libffi6 # not found
> ```
> 
> if above command failed. You can add repo from a previous Debian 10 to your sources for apt:
> 
> ```shell
> sudo nano /etc/apt/sources.list
> 
> # Add these lines should be in your sources
> deb http://deb.debian.org/debian bullseye main contrib non-free # Debian 11 repo
> deb http://deb.debian.org/debian buster main contrib non-free   # Debian 10 repo (add this)
> # ... Other packages bellow
> ```
> 
> **install rhasspy dependencies**
> 
> ```shell
> sudo apt install libffi6      # works
> sudo apt install libgfortran4 # works (rhasspy dependency)
> ```

Don't forget to run `sudo apt update` between adding the repos and installing the packages!
