### ISSUE TITLE
satellite TTS not working

### ISSUE THREAD

**Issue by tulth** [rhasspy/rhasspy#262]
If I run rhasspy 2.5.9, satellite TTS works great.

When I update to 2.5.11, satellite TTS no longer works.

If I downgrade to 2.5.9, satellite TTS works again.

This is true for my rpi 3b armv7 32-bit, and for a rpi 4b running aarch64.
Both are using docker.

The server is running in a docker image on an amd64 machine.  The server is running 2.5.11 in all cases.

I see the following error message:
```
[DEBUG:2021-11-30 20:48:50,896] rhasspyserver_hermes: TTS timeout will be 30 second(s)
[DEBUG:2021-11-30 20:48:50,901] rhasspyserver_hermes: -> TtsSay(text='speech test', site_id='hifiberry', lang=None, id='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='', volume=1.0)
[DEBUG:2021-11-30 20:48:50,901] rhasspyserver_hermes: Publishing 138 bytes(s) to hermes/tts/say
[DEBUG:2021-11-30 20:48:50,906] rhasspyremote_http_hermes: <- TtsSay(text='speech test', site_id='hifiberry', lang=None, id='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='', volume=1.0)
[DEBUG:2021-11-30 20:48:50,906] rhasspyremote_http_hermes: http://docker:12101/api/text-to-speech
[WARNING:2021-11-30 20:48:56,964] rhasspyremote_http_hermes: Expected audio/wav content type, got text/html; charset=utf-8
[DEBUG:2021-11-30 20:48:56,968] rhasspyremote_http_hermes: -> AudioPlayBytes(11 byte(s)) to hermes/audioServer/hifiberry/playBytes/5c15ff71-bac2-46af-af20-6473bf46a34d
[DEBUG:2021-11-30 20:48:56,972] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/hifiberry/playBytes/5c15ff71-bac2-46af-af20-6473bf46a34d, id=b63c3e0c-7293-4d08-b2c6-686c796e58b8)
[DEBUG:2021-11-30 20:48:56,972] rhasspyremote_http_hermes: -> TtsSayFinished(site_id='hifiberry', id='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='')
[DEBUG:2021-11-30 20:48:56,973] rhasspyremote_http_hermes: Publishing 86 bytes(s) to hermes/tts/sayFinished
[DEBUG:2021-11-30 20:48:56,973] rhasspyspeakers_cli_hermes: <- AudioPlayBytes(11 byte(s))
[DEBUG:2021-11-30 20:48:56,975] rhasspyspeakers_cli_hermes: ['aplay', '-q', '-t', 'wav', '-D', 'default:CARD=sndrpihifiberry']
[ERROR:2021-11-30 20:48:56,979] rhasspyspeakers_cli_hermes: handle_play
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 248, in convert_to_wav
    with io.BytesIO(sound_bytes) as sound_io, wave.open(sound_io, "rb"):
  File "/usr/lib/python3.7/wave.py", line 510, in open
    return Wave_read(f)
  File "/usr/lib/python3.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python3.7/wave.py", line 131, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 255, in convert_to_wav
    audio_data, sample_rate = soundfile.read(sound_file)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/soundfile.py", line 257, in read
    subtype, endian, format, closefd) as f:
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening <_io.BytesIO object at 0x7f82c4e9e8>: File contains data in an unknown format.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 81, in handle_play
    wav_bytes = self.convert_to_wav(sound_bytes)
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 265, in convert_to_wav
    temp_file.name, backends=self.audioread_backends
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
[DEBUG:2021-11-30 20:48:56,981] rhasspyspeakers_cli_hermes: -> AudioPlayError(error='', site_id='hifiberry', context='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='5c15ff71-bac2-46af-af20-6473bf46a34d')
[DEBUG:2021-11-30 20:48:56,982] rhasspyspeakers_cli_hermes: Publishing 140 bytes(s) to hermes/error/audioServer/play
[DEBUG:2021-11-30 20:48:56,985] rhasspyspeakers_cli_hermes: -> AudioPlayFinished(id='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='5c15ff71-bac2-46af-af20-6473bf46a34d')
[DEBUG:2021-11-30 20:48:56,985] rhasspyspeakers_cli_hermes: Publishing 99 bytes(s) to hermes/audioServer/hifiberry/playFinished
[DEBUG:2021-11-30 20:48:56,989] rhasspyserver_hermes: Handling AudioPlayError (topic=hermes/error/audioServer/play, id=b63c3e0c-7293-4d08-b2c6-686c796e58b8)
[DEBUG:2021-11-30 20:48:57,014] rhasspydialogue_hermes: <- TtsSayFinished(site_id='hifiberry', id='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='')
[DEBUG:2021-11-30 20:48:57,018] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=b63c3e0c-7293-4d08-b2c6-686c796e58b8)
[ERROR:2021-11-30 20:48:57,022] rhasspyserver_hermes: AudioPlayError(error='', site_id='hifiberry', context='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='5c15ff71-bac2-46af-af20-6473bf46a34d')
[ERROR:2021-11-30 20:48:57,024] rhasspyserver_hermes:
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1699, in api_text_to_speech
    results = await asyncio.gather(*aws)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1685, in speak
    say_chars_per_second=say_chars_per_second,
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 632, in speak_sentence
    raise AudioServerException(play_response.error)
rhasspyserver_hermes.AudioServerException
[DEBUG:2021-11-30 20:48:57,029] rhasspydialogue_hermes: <- AudioPlayFinished(id='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='5c15ff71-bac2-46af-af20-6473bf46a34d')


```

**Comment by tulth** [comment]
I notice this for a 2.5.9 working case:
```
[DEBUG:2021-11-30 20:56:13,752] rhasspyserver_hermes: Publishing 135 bytes(s) to hermes/tts/say
[DEBUG:2021-11-30 20:56:13,761] rhasspyremote_http_hermes: <- TtsSay(text='speech test', site_id='merkin', lang=None, id='9fd09346-01d5-4e2c-b4f5-18cfd8f273d0', session_id='', volume=1.0)
[DEBUG:2021-11-30 20:56:13,762] rhasspyremote_http_hermes: http://docker:12101/api/text-to-speech
[DEBUG:2021-11-30 20:56:15,236] rhasspyremote_http_hermes: -> AudioPlayBytes(50220 byte(s)) to hermes/audioServer/merkin/playBytes/9fd09346-01d5-4e2c-b4f5-18cfd8f273d0
```

compared to a 2.5.11 failing TTS case:
```
[DEBUG:2021-11-30 20:48:50,901] rhasspyserver_hermes: Publishing 138 bytes(s) to hermes/tts/say
[DEBUG:2021-11-30 20:48:50,906] rhasspyremote_http_hermes: <- TtsSay(text='speech test', site_id='hifiberry', lang=None, id='5c15ff71-bac2-46af-af20-6473bf46a34d', session_id='', volume=1.0)
[DEBUG:2021-11-30 20:48:50,906] rhasspyremote_http_hermes: http://docker:12101/api/text-to-speech
[WARNING:2021-11-30 20:48:56,964] rhasspyremote_http_hermes: Expected audio/wav content type, got text/html; charset=utf-8
[DEBUG:2021-11-30 20:48:56,968] rhasspyremote_http_hermes: -> AudioPlayBytes(11 byte(s)) to hermes/audioServer/hifiberry/playBytes/5c15ff71-bac2-46af-af20-6473bf46a34d
```

It seems like only part of the reply was received (83 bytes vs 50kbytes), and it got an unexpected content type.

**Comment by tulth** [comment]
on the server side (dns named "docker" and site id cobalt-rhasspy ), here is the working 2.5.9 log:
```
[DEBUG:2021-12-01 03:13:17,349] rhasspyserver_hermes: -> AudioToggleOff(site_id='cobalt-rhasspy')
[DEBUG:2021-12-01 03:13:17,350] rhasspyserver_hermes: Publishing 28 bytes(s) to hermes/audioServer/toggleOff
[DEBUG:2021-12-01 03:13:17,350] rhasspyserver_hermes: TTS timeout will be 30 second(s)
[DEBUG:2021-12-01 03:13:17,350] rhasspyserver_hermes: -> TtsSay(text='speech test', site_id='cobalt-rhasspy', lang=None, id='00985ede-5c03-4bba-a7ff-2d4cc7b9a1fd', session_id='', volume=1.0)
[DEBUG:2021-12-01 03:13:17,350] rhasspyserver_hermes: Publishing 143 bytes(s) to hermes/tts/say
[DEBUG:2021-12-01 03:13:17,395] rhasspytts_larynx_hermes: <- TtsSay(text='speech test', site_id='cobalt-rhasspy', lang=None, id='00985ede-5c03-4bba-a7ff-2d4cc7b9a1fd', session_id='', volume=1.0)
[DEBUG:2021-12-01 03:13:17,395] rhasspytts_larynx_hermes: Using WAV from cache: /profiles/en/tts/larynx/cache/1b93d6186227e476f3f6b48bd62b53f9.wav
[DEBUG:2021-12-01 03:13:17,395] rhasspytts_larynx_hermes: -> AudioPlayBytes(50220 byte(s)) to hermes/audioServer/cobalt-rhasspy/playBytes/00985ede-5c03-4bba-a7ff-2d4cc7b9a1fd
[DEBUG:2021-12-01 03:13:17,395] rhasspytts_larynx_hermes: Waiting for play finished (timeout=1.3877777777777778)
[DEBUG:2021-12-01 03:13:17,396] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/cobalt-rhasspy/playBytes/00985ede-5c03-4bba-a7ff-2d4cc7b9a1fd, id=2abc2262-d5fa-4c54-b4b8-733a6146702d)
[WARNING:2021-12-01 03:13:18,786] rhasspytts_larynx_hermes: Did not receive playFinished before timeout
[DEBUG:2021-12-01 03:13:18,787] rhasspytts_larynx_hermes: -> TtsSayFinished(site_id='cobalt-rhasspy', id='00985ede-5c03-4bba-a7ff-2d4cc7b9a1fd', session_id='')
[DEBUG:2021-12-01 03:13:18,787] rhasspytts_larynx_hermes: Publishing 91 bytes(s) to hermes/tts/sayFinished
[DEBUG:2021-12-01 03:13:18,788] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=2abc2262-d5fa-4c54-b4b8-733a6146702d)
[DEBUG:2021-12-01 03:13:18,788] rhasspydialogue_hermes: <- TtsSayFinished(site_id='cobalt-rhasspy', id='00985ede-5c03-4bba-a7ff-2d4cc7b9a1fd', session_id='')
[DEBUG:2021-12-01 03:13:18,789] rhasspyserver_hermes: -> AudioToggleOn(site_id='cobalt-rhasspy')
[DEBUG:2021-12-01 03:13:18,789] rhasspyserver_hermes: Publishing 28 bytes(s) to hermes/audioServer/toggleOn
```

and here is the failing 2.5.11 log:
```

[DEBUG:2021-12-01 03:14:21,057] rhasspyserver_hermes: -> AudioToggleOff(site_id='cobalt-rhasspy')
[DEBUG:2021-12-01 03:14:21,057] rhasspyserver_hermes: Publishing 28 bytes(s) to hermes/audioServer/toggleOff
[DEBUG:2021-12-01 03:14:21,057] rhasspyserver_hermes: TTS timeout will be 30 second(s)
[DEBUG:2021-12-01 03:14:21,057] rhasspyserver_hermes: -> TtsSay(text='speech test', site_id='hifiberry', lang=None, id='648bee7c-e632-411e-89cc-5b3818f08150', session_id='', volume=1.0)
[DEBUG:2021-12-01 03:14:21,057] rhasspyserver_hermes: Publishing 138 bytes(s) to hermes/tts/say
[DEBUG:2021-12-01 03:14:21,058] rhasspytts_larynx_hermes: <- TtsSay(text='speech test', site_id='hifiberry', lang=None, id='648bee7c-e632-411e-89cc-5b3818f08150', session_id='', volume=1.0)
[DEBUG:2021-12-01 03:14:21,058] rhasspytts_larynx_hermes: Using WAV from cache: /profiles/en/tts/larynx/cache/1b93d6186227e476f3f6b48bd62b53f9.wav
[DEBUG:2021-12-01 03:14:21,059] rhasspytts_larynx_hermes: -> AudioPlayBytes(50220 byte(s)) to hermes/audioServer/hifiberry/playBytes/648bee7c-e632-411e-89cc-5b3818f08150
[DEBUG:2021-12-01 03:14:21,059] rhasspytts_larynx_hermes: Waiting for play finished (timeout=1.3877777777777778)
[WARNING:2021-12-01 03:14:22,450] rhasspytts_larynx_hermes: Did not receive playFinished before timeout
[DEBUG:2021-12-01 03:14:22,450] rhasspytts_larynx_hermes: -> TtsSayFinished(site_id='hifiberry', id='648bee7c-e632-411e-89cc-5b3818f08150', session_id='')
[DEBUG:2021-12-01 03:14:22,450] rhasspytts_larynx_hermes: Publishing 86 bytes(s) to hermes/tts/sayFinished
[DEBUG:2021-12-01 03:14:22,452] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=803465e4-7ee9-47b0-86dd-5267ee8ee2e4)
[DEBUG:2021-12-01 03:14:22,452] rhasspydialogue_hermes: <- TtsSayFinished(site_id='hifiberry', id='648bee7c-e632-411e-89cc-5b3818f08150', session_id='')
[DEBUG:2021-12-01 03:14:22,452] rhasspyserver_hermes: -> AudioToggleOn(site_id='cobalt-rhasspy')
[DEBUG:2021-12-01 03:14:22,452] rhasspyserver_hermes: Publishing 28 bytes(s) to hermes/audioServer/toggleOn
```

I notice in the above, the site id is different in each case.  In the failing case I see the satellite site ID show up.  But I do not see the satellite site id on the passing case.  Maybe somehow that is the problem?

**Comment by tulth** [comment]
I tried 2.5.10 and remote tts does not work here for me.  So, 2.5.9 works, 2.5.10 fails.

**Comment by tulth** [comment]
I captured the satellite post data with python.

2.5.9:
```
INFO:root:POST request,
Path: /?play=false
Headers:
Host: crm-114:12121
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.7 aiohttp/3.6.2
Content-Length: 11
Content-Type: text/plain; charset=utf-8

Body:
speech test

192.168.10.7 - - [01/Dec/2021 10:57:55] "POST /?play=false HTTP/1.1" 200 -
```

2.5.10, this  time the site id is in the post:
```
INFO:root:POST request,
Path: /?play=false&siteId=hifiberry
Headers:
Host: crm-114:12121
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.7 aiohttp/3.7.4
Content-Length: 11
Content-Type: text/plain; charset=utf-8



Body:
speech test

192.168.10.45 - - [01/Dec/2021 11:00:25] "POST /?play=false&siteId=hifiberry HTTP/1.1" 200 -
```

**Comment by tulth** [comment]
I tried manually curling from the 2.5.11 server, and indeed the site id causes a problem.

2.5.9 style curl:
```
$ curl -X POST -s -d "speech test" 'http://docker.localdomain:12101/api/text-to-speech?play=false' --output response.wav 
$ ls -al response.wav
-rw-r--r--   1 tulth          tulth       50220 2021-12-01 11:26 response.wav
```

2.5.10 style curl with site id just gives back text, not a wave:
```
$ curl -X POST -s -d "speech test" 'http://docker.localdomain:12101/api/text-to-speech?play=false&siteId=hifiberry' --output response.wav 
$ ls -al response.wav
-rw-r--r--   1 tulth          tulth          11 2021-12-01 11:26 response.wav
$ cat response.wav
speech test
```

**Comment by tulth** [comment]
It is possible I have something setup wrong.  Let me know if you see anything!

I did try on the server settingTTS  satellites to:
- "hifiberry,other": just a text response not audio as above
- blank: this gave no response at all
- "hifiberry": one satellite only, just a text response not audio as above.

As a workaround right now I send the TTS to a rewriting server I whipped up that drops the site id and proxies this modified request to the real TTS server.

**Comment by tulth** [comment]
I would try and put in a PR if this is broken but I am not not clear on why the siteId goes to the base and what it is for.

**Comment by LeoLTM** [comment]
Great research man 👍🏻 

I'm facing the same problem...

**Comment by donburch888** [comment]
Firstly, this looks to me like a configuration issue rather than a bug in the program code.  I assume it's too late to debug this particular problem - by now either you have resolved it, or taken a different path.  

In future, or for anyone else with similar issues, I strongly recommend posting issues like this in the [Community Discourse (aka discussion forum)](https://community.rhasspy.org/) where it will get noticed a lot sooner.  

> I am not not clear on why the siteId goes to the base and what it is for.

My understanding is that 

1. The satellite is the device which hears the voice command, and so it is the one which manages the processing.
2. The satellite may do all the processing stages itself, or request another device to perform infdividual services.  For example a satellite running on a RasPi Zero can ask the base station (running on a RasPi 4 or NUC) to perform the cpu-intensive Speech-to-Text, Intent Recognition, and Text-to-Speech functions. On the base station, each such service has a list of satellite-IDs which it may accept requests from. 
3. Whenever a satellite requests the base station to perform a task, the base has to know where the result is to be returned. It is essential that each satellite has a unique SiteID set.


When posting an issue like this, please include details of base and satellites, including the profile from each.  Rather than take screenshots of configuration screens, you can copy and paste your Rhasspy profile from "Advanced" in the drop-down ![image](https://user-images.githubusercontent.com/60803198/176377110-16d2d8dc-9901-4985-b78e-e5cf1ab9a5e4.png)

**Comment by vdbrink** [comment]
Can anyone tell what the current status is?
Is TTL possible on a satellite with the latest Rhasspy version?

**Comment by donburch888** [comment]
vdbrink, the answer is yes, no and maybe; depending on what you are actually asking. 

Note that github issues is for reporting actual program code bugs.  if you have a question or problem, you should first check the rhasspy forum at [https://community.rhasspy.org/](https://community.rhasspy.org/) and raise a new thread there.
