### ISSUE TITLE
Porcupine update needed

### ISSUE THREAD

**Issue by s482dcaw** [rhasspy/rhasspy#265]
Porcupine updated picovoice console to generate v2.0 wake-word files. 
These do not work with the version of porcupine that is distributed with rhasspy as part of the rhasspy docker container

**Comment by ghost** [comment]
Same here for Rhasspy 2.5.11 deb file for raspberry.

**Comment by abetoret** [comment]
Same problem. Thanks.

**Comment by bylli79** [comment]
I have the same problem too.  
There are updates?  

Thank you

**Comment by nekromant** [comment]
I managed to update porcupine manually by downloading and replacing the files. The API changed a little, and now you have to pass your API key to porcupine, though it doesn't look like it's sending anything else back, save for the API Key.

**Comment by s482dcaw** [comment]
I have updated porcupine and modified rhasspy to work, but I do not know if it makes sense to send a pull request. 
My understanding is that the old version is cloud-free; it just works for everyone who doesn't want a custom wake word. 
The new version requires an API key, even when no custom word is used. This may work for me, but may not work for others, and I understand it's one or the other, you cannot have both.

**Comment by abetoret** [comment]
I've found the solution [here](https://community.rhasspy.org/t/picovoice-offline-voice-ai-engine-gets-free-tier-for-up-to-3-users/3328/8)

**Comment by bylli79** [comment]
> I've found the solution [here](https://community.rhasspy.org/t/picovoice-offline-voice-ai-engine-gets-free-tier-for-up-to-3-users/3328/8)

Would it be possible to commit with this fix?

**Comment by Santobert** [comment]
In case someone searches for this issue, the following error is reported via logs:

```txt
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__init__.py", line 254, in detection_thread_proc
    sensitivities=self.sensitivities,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/__init__.py", line 68, in create
    sensitivities=sensitivities)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 94, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
ValueError
```

I could solve this by using the keyword file from [this branch/tag](https://github.com/Picovoice/porcupine/tree/v1.9/resources/keyword_files)

**Comment by abetoret** [comment]
> > I've found the solution [here](https://community.rhasspy.org/t/picovoice-offline-voice-ai-engine-gets-free-tier-for-up-to-3-users/3328/8)
> 
> Would it be possible to commit with this fix?

Sorry, but I have customized code. Maybe in the next version it will be corrected.

**Comment by abetoret** [comment]
> In case someone searches for this issue, the following error is reported via logs:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__init__.py", line 254, in detection_thread_proc
>     sensitivities=self.sensitivities,
>   File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/__init__.py", line 68, in create
>     sensitivities=sensitivities)
>   File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 94, in __init__
>     raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
> ValueError
> ```
> 
> I could solve this by using the keyword file from [this branch/tag](https://github.com/Picovoice/porcupine/tree/v1.9/resources/keyword_files)

The ppn version of wakeword in config file has to match the pvporcupine version and the correct params model.

**Comment by Nailik** [comment]
> I have updated porcupine and modified rhasspy to work, but I do not know if it makes sense to send a pull request. 
> My understanding is that the old version is cloud-free; it just works for everyone who doesn't want a custom wake word. 
> The new version requires an API key, even when no custom word is used. This may work for me, but may not work for others, and I understand it's one or the other, you cannot have both. 
> 

My understanding is, that the new version only needs internet access once to verify the API key .

**Comment by glcos** [comment]
> I do not know if it makes sense to send a pull request.

@s482dcaw I believe it does make sense to make a PR. I also managed to make porcupine working after some struggling and code patching, but it would be nice to have a cleaner way of installing everything.

**Comment by LuisMalhadas** [comment]
Hello.

I have forked this project and have found a way of updating the pvporcupine to version 2.1.4.
It is inspired by the previous comments and resources.
It includes _undeprecating_ the library and model parameters, which AFAI understand are being used for foreign languages (non English).
commit [cf628aa35cc82b8863a2634262d464c588b7c065](https://github.com/LuisMalhadas/rhasspy-wake-porcupine-hermes/commit/cf628aa35cc82b8863a2634262d464c588b7c065)
This implies some changes also on the supervisor project.
It may also imply some changes to the Dockerfile, or at least I had to do it on my development environment. With which I wasn't really able to install locally without docker (I am using a macbook M1)

model and parameters files as well as the wake_word file all go into the _/profiles_ directory.
Unlike _keyword_path_ that requires only a partial path to the file, both _library_path_ and _model_path_ require full paths. This may be improved, but I feel that full paths give more freedom to the users.

So, I am coming here to revive the discussion and get some feedback, such so I can also understand if I should do a PR or not.

**Comment by lightsabata** [comment]
Hi @LuisMalhadas  , i've tried to use your fork to be able to run porcupine 2.1.4
Rhasspy launch but unfortunately porcupine seems to crash at startup with the following error code:

```
[ERROR] rhasspywake_porcupine_hermes: detection_thread_proc
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__init__.py", line 263, in detection_thread_proc
    model_path=self.model_path,
  File "/home/respeaker/.local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 82, in create
    sensitivities=sensitivities)
  File "/home/respeaker/.local/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 120, in __init__
    raise IOError("Couldn't find Porcupine's dynamic library at '%s'." % library_path)
OSError: Couldn't find Porcupine's dynamic library at 'libpv_porcupine.so'.
```

Overwise the rhasspy instance starts with all others plugins

thank you for your work and btw

**Comment by LuisMalhadas** [comment]
@lightsabata I feel that you are not uploading the library libpv_porcupine.so to '/profiles/es/porcupine/'
It could also be because you haven't set the correct branch: djfil for building...
But without more details on your process (how you got that error) I can't help much more.
Please let me know more! Perhaps you can submit an issue under my fork such so we don't pollute this rep with divergent issues.

**Comment by gerwim** [comment]
@LuisMalhadas Thanks for your work on your `djfil` branch!

Could you tell me the steps you used to build a docker image from your `djfil` branch? I'm trying to build with `NOBUILDX=1 scripts/build-docker.sh` on a Raspberry Pi 2 (armv7). However it will fail at the step which copies shared files: `COPY failed: file not found in build context or excluded by .dockerignore: stat download/shared/: file does not exist`.

When I look at the files, it seems `Makefile.in` downloads the shared files. So when running `make -f Makefile.in`, I'd get another error:
```
make -f Makefile.in
make: @SHELL@: No such file or directory
make: *** [Makefile.in:208: download-init] Error 127
```

Any guidance would be greatly appreciated.

**Comment by LuisMalhadas** [comment]
I had similar issue, and ended up copying the files to destination paths by hand.
There's probably a permission issue, or a typo on the path. 
You should also be sure that the docker build has the source path (where those files are locally) built on the expected path inside docker with the -v option.
I am afk, so can't help much more. Tomorrow I'll try to give more feedback

P.S. is it possible to have this working on a raspberry pi 2?? Afaik the version 3 was the minimum... No?

**Comment by gerwim** [comment]
@LuisMalhadas Thanks for your reply. It's not an issue with the source path. I simply do not have the predownloaded files. They are downloaded/generated (as far as I know) by the Makefile.

>  I am afk, so can't help much more. Tomorrow I'll try to give more feedback

Would be much appreciated!

> P.S. is it possible to have this working on a raspberry pi 2?? Afaik the version 3 was the minimum... No?

I have `rhasspy` currently working on a Pi 2. I just want a custom wake word, which led me into this rabbit hole 😛

**Comment by LuisMalhadas** [comment]
Hello @gerwim 
I have executed that script and I got to the same issue.
being, that I had not downloaded the system dependencies.
Have you ran: 
`NOBUILDX=1 scripts/download-dependencies.sh`
Although I have executed that as well, I still had some files that don't exist anymore, but I am also testing for an M1, so I'm not the best reference.

Also, sorry for such a late reply, I have been busy.

**Comment by gerwim** [comment]
Hi @LuisMalhadas, no worries. No need for an apology. You don't owe me anything ;-). 

But yes, I have tried to download them. These don't download the shares binaries. I only found references to it in the Makefile. 

I will ask upstream on how to build the project. I'll let you know if I have an answer.

**Comment by LuisMalhadas** [comment]
@gerwim 

`julius-4.5_armv7.tar.gz
kaldi-2020_armv7.tar.gz
kaldi-2021_armv7.tar.gz
kenlm-20200308_armv7.tar.gzprepre.gz
kenlm-20210107_armv7.tar.gz
marisa_trie-0.7.7-cp39-cp39-linux_armv7l.whl
mecab_python3-1.0.4-cp39-cp39-linux_armv7l.whl
mitlm-0.4.2-armv7.tar.gz
nanotts-20200520_armv7.tar.gz
numpy-1.22.3-cp39-cp39-linux_armv7l.whl
onnxruntime-1.6.0-cp37-cp37m-linux_armv7l.whl
onnxruntime-1.7.0-cp38-cp38-linux_armv7l.whl
onnxruntime-1.9.0-cp37-cp37m-linux_armv7l.whl
onnxruntime-1.9.0-cp39-cp39-linux_armv7l.whl
onnxruntime-1.9.0-cp310-cp310-linux_armv7l.whl
onnxruntime-1.9.1-cp36-cp36m-linux_armv7l.whl
onnxruntime-1.9.1-cp37-cp37m-linux_armv7l.whl
onnxruntime-1.9.1-cp38-cp38-linux_armv7l.whl
onnxruntime-1.9.1-cp39-cp39-linux_armv7l.whl
onnxruntime-1.9.1-cp310-cp310-linux_armv7l.whl
onnxruntime-1.10.0-cp39-cp39-linux_armv7l.whl
opengrm-1.3.4_armv7.tar.gz
phonetisaurus-0.3.0-py3-none-linux_armv7l (1).whl
phonetisaurus-0.3.0-py3-none-linux_armv7l.whl
phonetisaurus-2019_armv7.tar.gz
python_crfsuite-0.9.8-cp39-cp39-linux_armv7l.whl`

This is the list of files I have, under download/armv7

`num2words_0.5.10-sv.tar.gz
pocketsphinx-python.tar.gz`

And these under download/shared

I have built the docker images in the Mac, and I do recall having to search for some files and download them by hand.
My objective was to have it built for a raspberry pi 4. Therefore I never really used any of these scripts.
Also to be noted that I wasn't able to build everything, and stuff like deep speech was excluded.

`./configure --disable-deepspeech --disable-larynx --enable-in-place --prefix=${APP_DIR}/.venv`
With APP_DIR set to /usr/lib/rhasspy

If all you want is the where have I found the binaries that you are missing, I don't remember, can't help there sorry.

Another thing I noticed is that these scripts don't seem to be updated. Meaning that they are downloading to the folder download, but then docker is looking for download/arch or download/shared, which don't exist.

**Comment by LuisMalhadas** [comment]
Actually now looking at your error, although not clear from the message, but I'm now betting download/shared folder does not exist. Try to create it.

**Comment by gerwim** [comment]
@LuisMalhadas Thanks for your answers. I managed to get it building (even though it takes ages because the rPI2 is just slow and doing other stuff as well). Basically, a gist (this includes downloading all correct files):

1. `git clone --recurse-submodules -j8 https://github.com/gerwim/rhasspy` (I made a fork of your `djfil` branch and committed to master
2. `cd rhasspy`
3. `./configure --disable-dependency-check`
4. `make`
5. Start a docker build: `NOBUILDX=1 scripts/build-docker.sh`

I think this should work, like I said, it's still doing it's thing... ;-)
