### ISSUE TITLE
Matrix voice not working with Rhasspy 2.5.11 (deb package) but works ins 2.4.20 (docker version)

### ISSUE THREAD

**Issue by ch-rigu** [rhasspy/rhasspy#266]
Hi, I have a matrix voice device connected to the raspberry working properly, but is not working with Rhasspy 2.5.11 (Debian package). If I use the docker version (2.4.20) it works but the docker version doesn't play any sound :(

this is my profile:
```
{
    "handle": {
        "remote": {
            "url": "http://localhost:1111"
        },
        "system": "remote"
    },
    "intent": {
        "system": "fsticuffs"
    },
    "microphone": {
        "arecord": {
            "device": "hw:CARD=MATRIXIOSOUND,DEV=0"
        },
        "system": "arecord"
    },
    "sounds": {
        "aplay": {
            "device": "hw:CARD=Headphones,DEV=0"
        },
        "system": "aplay"
    },
    "speech_to_text": {
        "system": "pocketsphinx"
    },
    "text_to_speech": {
        "system": "nanotts"
    },
    "wake": {
        "porcupine": {
            "keyword_path": "jarvis_raspberry-pi.ppn"
        },
        "system": "porcupine"
    }
}```

when I click on "wake up" button I got this on the console:
````
[DEBUG:2021-12-15 11:12:26,261] rhasspyserver_hermes: -> HotwordDetected(model_id='default', model_version='', model_type='personal', current_sensitivity=1.0, site_id='default', session_id=None, send_audio_captured=None, lang=None, custom_entities=None)
[DEBUG:2021-12-15 11:12:26,263] rhasspyserver_hermes: Publishing 199 bytes(s) to hermes/hotword/default/detected
[DEBUG:2021-12-15 11:12:26,264] rhasspyserver_hermes: Waiting for intent (session_id=None)
[DEBUG:2021-12-15 11:12:26,266] rhasspyserver_hermes: Subscribed to hermes/error/nlu
[DEBUG:2021-12-15 11:12:26,277] rhasspyserver_hermes: <- HotwordDetected(model_id='default', model_version='', model_type='personal', current_sensitivity=1.0, site_id='default', session_id=None, send_audio_captured=None, lang=None, custom_entities=None)
[WARNING:2021-12-15 11:12:26,280] rhasspyserver_hermes: Dialogue management is disabled. ASR will NOT be automatically enabled.
[ERROR:2021-12-15 11:12:56,294] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 943, in api_listen_for_command
    async for response in core.publish_wait(handle_intent(), [], message_types):
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 995, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError[DEBUG:2021-12-15 11:12:26,261] rhasspyserver_hermes: -> HotwordDetected(model_id='default', model_version='', model_type='personal', current_sensitivity=1.0, site_id='default', session_id=None, send_audio_captured=None, lang=None, custom_entities=None)
[DEBUG:2021-12-15 11:12:26,263] rhasspyserver_hermes: Publishing 199 bytes(s) to hermes/hotword/default/detected
[DEBUG:2021-12-15 11:12:26,264] rhasspyserver_hermes: Waiting for intent (session_id=None)
[DEBUG:2021-12-15 11:12:26,266] rhasspyserver_hermes: Subscribed to hermes/error/nlu
[DEBUG:2021-12-15 11:12:26,277] rhasspyserver_hermes: <- HotwordDetected(model_id='default', model_version='', model_type='personal', current_sensitivity=1.0, site_id='default', session_id=None, send_audio_captured=None, lang=None, custom_entities=None)
[WARNING:2021-12-15 11:12:26,280] rhasspyserver_hermes: Dialogue management is disabled. ASR will NOT be automatically enabled.
[ERROR:2021-12-15 11:12:56,294] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 943, in api_listen_for_command
    async for response in core.publish_wait(handle_intent(), [], message_types):
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 995, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
````

Any help is appreciated !
Cheers.

**Comment by Sturi2011** [comment]
Hi,

the problem is probaly, that Matrix Voice driver can handle only some specific audio formats. 
You have to transcode the stream to the needs of Matrix Voice.  

I have managed it with a script and sox.

Look at 
https://community.rhasspy.org/t/picovoice-offline-voice-ai-engine-gets-free-tier-for-up-to-3-users/3328/8?u=sturi2011

You can test it with the Speak command on home screen.


Greetings 

Andreas
