### ISSUE TITLE
Microphone found but didn't get "working"-state

### ISSUE THREAD

**Issue by pabatribick** [rhasspy/rhasspy#275]
My USB Microphone (Samson Meteorite Mic) is detected by Rhasspy (PyAudio)c and listed on the system devices.

If I click on "test" it will not change the state like the documentation to "working!" in the dropdownbox.

My console output is following after i click test:

`[DEBUG:2022-02-06 11:51:42,698] rhasspyserver_hermes: -> AudioGetDevices(modes=[<AudioDeviceMode.INPUT: 'input'>], site_id='default', id='17eec1ab-2626-4be6-bb59-d8aa7e10bc4d', test=True)
[DEBUG:2022-02-06 11:51:42,700] rhasspyserver_hermes: Publishing 101 bytes(s) to rhasspy/audioServer/getDevices
[DEBUG:2022-02-06 11:51:42,705] rhasspymicrophone_pyaudio_hermes: <- AudioGetDevices(modes=[<AudioDeviceMode.INPUT: 'input'>], site_id='default', id='17eec1ab-2626-4be6-bb59-d8aa7e10bc4d', test=True)
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,706] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
[ERROR:2022-02-06 11:51:42,712] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,716] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,718] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,721] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,723] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,727] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,728] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,729] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
[ERROR:2022-02-06 11:51:42,731] rhasspymicrophone_pyaudio_hermes: get_microphone_working ({device_name})
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 280, in get_microphone_working
    input=True,
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
[DEBUG:2022-02-06 11:51:42,740] rhasspymicrophone_pyaudio_hermes: -> AudioDevices(devices=[AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='0', name='bcm2835 Headphones: - (hw:0,0)', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='1', name='Samson Meteorite Mic: USB Audio (hw:1,0)*', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='2', name='sysdefault', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='3', name='lavrate', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='4', name='samplerate', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='5', name='speexrate', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='6', name='upmix', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='7', name='vdownmix', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='8', name='default', description='', working=False), AudioDevice(mode=<AudioDeviceMode.INPUT: 'input'>, id='9', name='dmix', description='', working=False)], site_id='default', id='17eec1ab-2626-4be6-bb59-d8aa7e10bc4d')
[DEBUG:2022-02-06 11:51:42,741] rhasspymicrophone_pyaudio_hermes: Publishing 1001 bytes(s) to rhasspy/audioServer/devices
[DEBUG:2022-02-06 11:51:42,758] rhasspyserver_hermes: Handling AudioDevices (topic=rhasspy/audioServer/devices, id=dfed8f53-66fb-47ba-b88f-063db9a321af)
`

are the some problems with the python lib? All requirements should be installed, followed like the documentation. Microphone is working What's the problem now? How to fix that?

**Comment by pablinho1023** [comment]
I am having the same problem and seems like all the problems like this just remain open. This is my log:
DEBUG:2022-09-10 19:00:54,183] rhasspyserver_hermes: Handling AudioDevices (topic=rhasspy/audioServer/devices, id=dc823bdb-ff0d-48e0-869b-88ba43e3fea0)
[DEBUG:2022-09-10 19:00:54,104] rhasspyserver_hermes: Publishing 101 bytes(s) to rhasspy/audioServer/getDevices
[DEBUG:2022-09-10 19:00:54,102] rhasspyserver_hermes: -> AudioGetDevices(modes=[<AudioDeviceMode.INPUT: 'input'>], site_id='default', id='5451f3bb-96cf-40eb-9459-5913e2bbffaf', test=True)
[DEBUG:2022-09-10 19:00:51,060] rhasspyserver_hermes: Handling AudioDevices (topic=rhasspy/audioServer/devices, id=1603105a-d520-4f60-8700-e15619eb1942)

**Comment by S-Docker** [comment]
Same, glad to see I can't find anything here or anywhere else after hours of trying to find out why this issue exists and how to solve it despite people mentioning it months ago.

**Comment by pablinho1023** [comment]
> Same, glad to see I can't find anything here or anywhere else after hours of trying to find out why this issue exists and how to solve it despite people mentioning it months ago.

I got it working by changing the input to "arecord" then clicking test and from the list there was one that said "working" selecting that one made it work

**Comment by S-Docker** [comment]
And to narrow it down even further... if I stop the home assistant container, the microphone works over arecord

**Comment by S-Docker** [comment]
For anyone who may come across this issue running home assistant and rhasspy in containers, this is what has fixed it (for now...):
Order of operations:
- stop the containers
- plug the audio devices back in
 - restart pi
 - start rhasspy container
 - start HA container

Doing it in this exact order allowed arecord to be used and the mic to work, if you start HA container first then it seems to interfere for some reason. 

No idea how long it'll stay working for or if it'll have a knock on effect on my next steps but maybe it'll work for you too.

**Comment by pablinho1023** [comment]
Yes, it worked out of the box in HA for me. I would suggest to try all the posible inputs and see wheter if some say working. Also, check closely every line, because the working doesn't show on the end always, sometimes is mid sentence.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
