### ISSUE TITLE
Run Rhasspy on Raspberry Pi 4

### ISSUE THREAD

**Issue by klues** [rhasspy/rhasspy#290]
Hello,
thanks for this amazing project which I would very much like to try!

However unfortunately I'm not managing to get it running on Rasperry Pi 4 with standard 32bit Raspberry Pi OS.

First I tried the deb package installation like described here: https://rhasspy.readthedocs.io/en/latest/installation/#debian
I installed the current `armhf` package. Installation worked, but on starting I'm getting this error on console:
```
CTraceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 13, in <module>
    import soundfile
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/soundfile.py", line 16, in <module>
    from ctypes.util import find_library as _find_library
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

The WebUI works, but none of the recognition / text-to-speech things etc. is working.

Second I tried to install as described here: https://rhasspy.readthedocs.io/en/latest/installation/#virtual-environment
Everything worked until `make install` stopped with this error:
```
ERROR: Could not find a version that satisfies the requirement onnxruntime~=1.6.0 (from larynx~=0.3.0->rhasspy==2.5.11) (from versions: none)
ERROR: No matching distribution found for onnxruntime~=1.6.0 (from larynx~=0.3.0->rhasspy==2.5.11)

```

Thanks for any help and suggestions!

**Comment by klues** [comment]
I've fixed the first error with `sudo apt-get install libffi6`
However, now I'm still [not able to record audio](https://github.com/rhasspy/rhasspy/issues/293) and also get a [TrainingException](https://github.com/rhasspy/rhasspy/issues/294).
