### ISSUE TITLE
Pyaudio invalid number of channels and arecord also not working

### ISSUE THREAD

**Issue by klues** [rhasspy/rhasspy#293]
I'm trying to use PyAudio for recording, but I get this in console:
```
[ERROR:2022-08-08 16:58:48,716] rhasspymicrophone_pyaudio_hermes: record
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-microphone-pyaudio-hermes/rhasspymicrophone_pyaudio_hermes/__init__.py", line 119, in record
    stream_callback=callback,
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
```
I'm using a Raspberry Pi 4 with a Jabra speaker/mic attached.
I've also tried `arecord`, but it also doesn't work. However starting `arecord test.wav` manually on console works.

**Comment by klues** [comment]
I'm now using "arecord" for audio recording and although it doesn't seem to work using the "Test" Button, it actually works for recording after wakeword recognition.
