### ISSUE TITLE
Training failed exception

### ISSUE THREAD

**Issue by klues** [rhasspy/rhasspy#294]
On a Rasberry Pi 4 I get this exception on training in the web interface:
```
TrainingFailedException: Command '['fstcompile', '--isymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--osymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/G.fst.unsorted']' returned non-zero exit status 1.
```

It's a fresh installation, no special settings or configuration.
This is the full log from the console:
```
[DEBUG:2022-08-08 17:18:12,298] rhasspyserver_hermes: Publishing 44 bytes(s) to hermes/asr/toggleOn
[DEBUG:2022-08-08 17:18:12,310] rhasspyasr_kaldi_hermes: <- AsrToggleOn(site_id='default', reason=<AsrToggleReason.PLAY_AUDIO: 'playAudio'>)
[DEBUG:2022-08-08 17:18:12,310] rhasspyasr_kaldi_hermes: Enabled
[INFO:2022-08-08 17:18:23,712] rhasspyserver_hermes: Starting training
[DEBUG:2022-08-08 17:18:23,718] rhasspyserver_hermes: Loading sentences from [PosixPath('/home/pi/.config/rhasspy/profiles/de/sentences.ini')]
[DEBUG:2022-08-08 17:18:23,721] rhasspyserver_hermes: Generating intent graph
[DEBUG:2022-08-08 17:18:23,728] rhasspynlu.ini_jsgf: Loaded ini file
[DEBUG:2022-08-08 17:18:23,742] rhasspyserver_hermes: Writing /home/pi/.config/rhasspy/profiles/de/intent_graph.pickle.gz
[DEBUG:2022-08-08 17:18:23,747] rhasspyserver_hermes: Finished writing /home/pi/.config/rhasspy/profiles/de/intent_graph.pickle.gz
[DEBUG:2022-08-08 17:18:23,755] rhasspyserver_hermes: Subscribed to rhasspy/asr/default/trainSuccess
[DEBUG:2022-08-08 17:18:23,756] rhasspyserver_hermes: Subscribed to hermes/error/asr
[DEBUG:2022-08-08 17:18:23,757] rhasspyserver_hermes: Subscribed to rhasspy/nlu/default/trainSuccess
[DEBUG:2022-08-08 17:18:23,758] rhasspyserver_hermes: Subscribed to hermes/error/nlu
[DEBUG:2022-08-08 17:18:23,763] rhasspyserver_hermes: -> AsrTrain
[DEBUG:2022-08-08 17:18:23,763] rhasspyserver_hermes: Publishing 567 bytes(s) to rhasspy/asr/default/train
[DEBUG:2022-08-08 17:18:23,768] rhasspyserver_hermes: -> NluTrain
[DEBUG:2022-08-08 17:18:23,769] rhasspyserver_hermes: Publishing 567 bytes(s) to rhasspy/nlu/default/train
[DEBUG:2022-08-08 17:18:23,784] rhasspyasr_kaldi_hermes: <- AsrTrain
[DEBUG:2022-08-08 17:18:23,785] rhasspyasr_kaldi_hermes: Loading base dictionary from /home/pi/.config/rhasspy/profiles/de/kaldi/base_dictionary.txt
[DEBUG:2022-08-08 17:18:23,785] rhasspynlu_hermes: <- NluTrain
[DEBUG:2022-08-08 17:18:23,790] rhasspynlu_hermes: Loading /home/pi/.config/rhasspy/profiles/de/intent_graph.pickle.gz
[DEBUG:2022-08-08 17:18:23,799] rhasspynlu_hermes: -> NluTrainSuccess(id='1bbb8186-8959-4e2b-81bd-62954f68d24b')
[DEBUG:2022-08-08 17:18:23,807] rhasspynlu_hermes: Publishing 46 bytes(s) to rhasspy/nlu/default/trainSuccess
[DEBUG:2022-08-08 17:18:23,811] rhasspyserver_hermes: Handling NluTrainSuccess (topic=rhasspy/nlu/default/trainSuccess, id=70e93fe5-0e38-4a18-ae6f-2cd4b11a66ef)
[DEBUG:2022-08-08 17:18:41,063] rhasspyasr_kaldi_hermes: Loading base dictionary from /home/pi/.config/rhasspy/profiles/de/kaldi_custom_words.txt
[DEBUG:2022-08-08 17:18:41,064] rhasspyasr_kaldi_hermes: Loading /home/pi/.config/rhasspy/profiles/de/intent_graph.pickle.gz
[DEBUG:2022-08-08 17:18:41,067] rhasspyasr_kaldi_hermes: Starting training
[DEBUG:2022-08-08 17:18:41,068] rhasspyasr_kaldi.train: Using kaldi at /usr/lib/rhasspy/lib/kaldi
[DEBUG:2022-08-08 17:18:41,070] rhasspyasr_kaldi.train: Writing G.fst directly
[DEBUG:2022-08-08 17:18:41,078] rhasspyasr_kaldi.train: Writing pronunciation dictionary
[WARNING:2022-08-08 17:18:41,079] rhasspynlu.g2p: Missing word 'spät'
[WARNING:2022-08-08 17:18:41,079] rhasspynlu.g2p: Missing word 'heiß'
[DEBUG:2022-08-08 17:18:41,081] rhasspynlu.g2p: Guessing pronunciations for {'spät', 'heiß'}
[DEBUG:2022-08-08 17:18:41,083] rhasspynlu.g2p: ['/usr/lib/rhasspy/bin/phonetisaurus-apply', '--model', '/home/pi/.config/rhasspy/profiles/de/kaldi/g2p.fst', '--word_list', '/tmp/tmp8o_rmfe_', '--nbest', '1']
[DEBUG:2022-08-08 17:18:45,664] rhasspynlu.g2p: Wrote missing words to /home/pi/.config/rhasspy/profiles/de/kaldi_unknown_words.txt
[DEBUG:2022-08-08 17:18:45,668] rhasspyasr_kaldi.train: Wrote dictionary to /home/pi/.config/rhasspy/profiles/de/kaldi/dictionary.txt
[DEBUG:2022-08-08 17:18:45,670] rhasspyasr_kaldi.train: Wrote language model to /home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt
[DEBUG:2022-08-08 17:18:45,681] rhasspyasr_kaldi.train: Generating lexicon
[DEBUG:2022-08-08 17:18:45,691] rhasspyasr_kaldi.train: ['bash', '/usr/lib/rhasspy/lib/kaldi/egs/wsj/s5/utils/prepare_lang.sh', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict', '<unk>', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/lang', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang']
/usr/lib/rhasspy/lib/kaldi/egs/wsj/s5/utils/prepare_lang.sh /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict <unk> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/lang /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang
Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/silence_phones.txt ...
--> reading /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/silence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/silence_phones.txt is OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/optional_silence.txt ...
--> reading /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/optional_silence.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/optional_silence.txt is OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/nonsilence_phones.txt ...
--> reading /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/nonsilence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/nonsilence_phones.txt is OK

Checking disjoint: silence_phones.txt, nonsilence_phones.txt
--> disjoint property is OK.

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/lexicon.txt
--> reading /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/lexicon.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/lexicon.txt is OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/extra_questions.txt ...
--> reading /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/extra_questions.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/extra_questions.txt is OK
--> SUCCESS [validating dictionary directory /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict]

**Creating /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/lexiconp.txt from /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/local/dict/lexicon.txt
fstaddselfloops /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/wdisambig_phones.int /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/wdisambig_words.int 
prepare_lang.sh: validating output directory
utils/validate_lang.pl /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang
Checking existence of separator file
separator file /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/subword_separator.txt is empty or does not exist, deal in word case.
Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones.txt ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones.txt is OK

Checking words.txt: #0 ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt is OK

Checking disjoint: silence.txt, nonsilence.txt, disambig.txt ...
--> silence.txt and nonsilence.txt are disjoint
--> silence.txt and disambig.txt are disjoint
--> disambig.txt and nonsilence.txt are disjoint
--> disjoint property is OK

Checking sumation: silence.txt, nonsilence.txt, disambig.txt ...
--> found no unexplainable phones in phones.txt

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/context_indep.{txt, int, csl} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 15 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/context_indep.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/context_indep.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/context_indep.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/context_indep.csl corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/context_indep.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/context_indep.{txt, int, csl} are OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/nonsilence.{txt, int, csl} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 404 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/nonsilence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/nonsilence.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/nonsilence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/nonsilence.csl corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/nonsilence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/nonsilence.{txt, int, csl} are OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/silence.{txt, int, csl} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 15 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/silence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/silence.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/silence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/silence.csl corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/silence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/silence.{txt, int, csl} are OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.{txt, int, csl} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 1 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.csl corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.{txt, int, csl} are OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.{txt, int, csl} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 2 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.csl corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.{txt, int, csl} are OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/roots.{txt, int} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 70 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/roots.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/roots.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/roots.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/roots.{txt, int} are OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/sets.{txt, int} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 70 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/sets.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/sets.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/sets.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/sets.{txt, int} are OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/extra_questions.{txt, int} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 12 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/extra_questions.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/extra_questions.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/extra_questions.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/extra_questions.{txt, int} are OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/word_boundary.{txt, int} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 419 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/word_boundary.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/word_boundary.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/word_boundary.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/word_boundary.{txt, int} are OK

Checking optional_silence.txt ...
--> reading /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/optional_silence.txt is OK

Checking disambiguation symbols: #0 and #1
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.txt has "#0" and "#1"
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/disambig.txt is OK

Checking topo ...

Checking word_boundary.txt: silence.txt, nonsilence.txt, disambig.txt ...
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/word_boundary.txt doesn't include disambiguation symbols
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/word_boundary.txt is the union of nonsilence.txt and silence.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/word_boundary.txt is OK

Checking word-level disambiguation symbols...
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/phones/wdisambig.txt exists (newer prepare_lang.sh)
Checking word_boundary.int and disambig.int
--> generating a 47 word/subword sequence
--> resulting phone sequence from L.fst corresponds to the word sequence
--> L.fst is OK
--> generating a 92 word/subword sequence
--> resulting phone sequence from L_disambig.fst corresponds to the word sequence
--> L_disambig.fst is OK

Checking /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/oov.{txt, int} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 1 entry/entries in /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/oov.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/oov.int corresponds to /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/oov.txt
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/oov.{txt, int} are OK

--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/L.fst is olabel sorted
--> /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/L_disambig.fst is olabel sorted
--> SUCCESS [validating lang directory /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang]
[DEBUG:2022-08-08 17:18:49,084] rhasspyasr_kaldi.train: ['fstcompile', '--isymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--osymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/G.fst.unsorted']
FATAL: FstCompiler: Symbol "spät" is not mapped to any integer arc ilabel, symbol table = /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt, source = /home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt, line = 4
[ERROR:2022-08-08 17:18:49,180] rhasspyasr_kaldi_hermes: train
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-asr-kaldi-hermes/rhasspyasr_kaldi_hermes/__init__.py", line 648, in handle_train
    cancel_prob=self.cancel_probability,
  File "/usr/lib/rhasspy/rhasspy-asr-kaldi/rhasspyasr_kaldi/train.py", line 236, in train
    cancel_prob=cancel_prob,
  File "/usr/lib/rhasspy/rhasspy-asr-kaldi/rhasspyasr_kaldi/train.py", line 526, in train_kaldi
    subprocess.check_call(compile_grammar, cwd=model_dir, env=extended_env)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['fstcompile', '--isymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--osymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/G.fst.unsorted']' returned non-zero exit status 1.
[DEBUG:2022-08-08 17:18:49,201] rhasspyasr_kaldi_hermes: -> AsrError(error="Command '['fstcompile', '--isymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--osymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/G.fst.unsorted']' returned non-zero exit status 1.", site_id='default', context=None, session_id='1bbb8186-8959-4e2b-81bd-62954f68d24b')
[DEBUG:2022-08-08 17:18:49,202] rhasspyasr_kaldi_hermes: Publishing 519 bytes(s) to hermes/error/asr
[DEBUG:2022-08-08 17:18:49,207] rhasspyserver_hermes: Handling AsrError (topic=hermes/error/asr, id=70e93fe5-0e38-4a18-ae6f-2cd4b11a66ef)
[ERROR:2022-08-08 17:18:49,213] rhasspyserver_hermes: AsrError(error="Command '['fstcompile', '--isymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--osymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/G.fst.unsorted']' returned non-zero exit status 1.", site_id='default', context=None, session_id='1bbb8186-8959-4e2b-81bd-62954f68d24b')
[ERROR:2022-08-08 17:18:49,217] rhasspyserver_hermes: Command '['fstcompile', '--isymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--osymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/G.fst.unsorted']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1313, in api_train
    result = await core.train()
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 472, in train
    raise TrainingFailedException(reason=asr_response.error)
rhasspyserver_hermes.TrainingFailedException: Command '['fstcompile', '--isymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--osymbols=/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt', '/home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/G.fst.unsorted']' returned non-zero exit status 1.

```

**Comment by LuisMalhadas** [comment]
I would say you have a typo on your sentences.ini:

FATAL: FstCompiler: Symbol "spät" is not mapped to any integer arc ilabel, symbol table = /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt, source = /home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt, line = 4

**Comment by klues** [comment]
Thanks for the hint, I've now replaced `spät` with `spaet` and `heiß` with `heiss` and it works 👍 
Sorry, I obviously didn't read the messages carefully enough. However as an improvement I would propose that either it should be possible to use special characters like these in words or that the default configurations (in this case German) shouldn't contain these characters.

**Comment by klues** [comment]
I've now run into the same issue, but in a way that I cannot easily solve on my own.
I've added a number range like `(0..100)` to a sentence and now I'm getting this error on training:
```
FATAL: FstCompiler: Symbol "fünf" is not mapped to any integer arc ilabel, symbol table = /home/pi/.config/rhasspy/profiles/de/kaldi/model/data/lang/words.txt, source = /home/pi/.config/rhasspy/profiles/de/kaldi/language_model.txt, line = 517
```
So the numbers are somehow translated to the german words and afterwards training is failing, because the auto-generated words are including special characters like `ü` in this case.

**Comment by klues** [comment]
I've fixed the german numbers issue in this PR: https://github.com/rhasspy/rhasspy-nlu/pull/16/files
To temporarily fix it, it's possible to just clone my fork at https://github.com/klues/rhasspy-nlu to the folder `/usr/lib/rhasspy/rhasspy-nlu/` (rename the existing folder to another name before).

**Comment by shummo** [comment]
HI! What should be here the problem?

`[DEBUG:2022-11-16 18:59:26,749] rhasspyasr_kaldi.train: ['fstcompile', '--isymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--osymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/share/rhasspy/profiles/en/kaldi/language_model.txt', '/share/rhasspy/profiles/en/kaldi/model/data/lang/G.fst.unsorted']
FATAL: FstCompiler: Symbol "bw_test" is not mapped to any integer arc ilabel, symbol table = /share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt, source = /share/rhasspy/profiles/en/kaldi/language_model.txt, line = 147
[ERROR:2022-11-16 18:59:26,796] rhasspyasr_kaldi_hermes: train`

what is the problem with bw_test entity name? Or what to do to correct it in rhasspy?


EDIT: The problem must be with the "_" in the name.  WHat should I do, if i cant rename all of my entities with such name?

**Comment by ikolsteren** [comment]
I think I am getting a similar issue
I can do covers with home assistant no problem
But something with my switches and lights returns this:
`TrainingFailedException: Command '['fstcompile', '--isymbols=/profiles/en/kaldi/model/data/lang/words.txt', '--osymbols=/profiles/en/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/profiles/en/kaldi/language_model.txt', '/profiles/en/kaldi/model/data/lang/G.fst.unsorted']' returned non-zero exit status 1.`

**Comment by Sitruk** [comment]
> I think I am getting a similar issue I can do covers with home assistant no problem But something with my switches and lights returns this: `TrainingFailedException: Command '['fstcompile', '--isymbols=/profiles/en/kaldi/model/data/lang/words.txt', '--osymbols=/profiles/en/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/profiles/en/kaldi/language_model.txt', '/profiles/en/kaldi/model/data/lang/G.fst.unsorted']' returned non-zero exit status 1.`

I'm getting the same error. It doesnt like words, but I'm not seeing where it pulled them from and how I can fix them. Some of the words I can't really see what they were supposed to be.

**Comment by ikolsteren** [comment]
I changed my speech to text to ARPA and was able to get my training.

**Comment by Sitruk** [comment]
It ended up just being a bunch of random things it couldn't resolve. I kind of gave up bc the response time to a request is unusably slow. Unless I did something wrong.
