### ISSUE TITLE
AssertionError: Missing slot $hass/entities,light

### ISSUE THREAD

**Issue by mrLeonTheMaster** [rhasspy/rhasspy#307]
I am using Rhasspy Hass.io addon and i am getting `AssertionError: Missing slot $hass/entities,light`.

I have light entities in Home Assistant.

**Comment by Jazz-ha** [comment]
**Also** experiencing this **issue.**
relevent log:

[ERROR:2023-02-13 18:05:38,828] rhasspyserver_hermes: Missing slot $hass/entities,light
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1313, in api_train
    result = await core.train()
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 365, in train
    word_transform=word_transform,
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/train.py", line 106, in sentences_to_graph
    sentences, replacements=replacements, add_intent_weights=add_intent_weights
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 426, in sentences_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 194, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 100, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 194, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 124, in expression_to_graph
    expand_slots=expand_slots,
  File "/usr/lib/rhasspy/rhasspy-nlu/rhasspynlu/jsgf_graph.py", line 206, in expression_to_graph
    assert slot_values, f"Missing slot {slot_name}"
AssertionError: Missing slot $hass/entities,light
[DEBUG:2023-02-13 18:05:38,737] rhasspynlu.slots: Running program for slot rhasspy/number,1,100,1: ['/usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/en/slot_programs/rhasspy/number', '1', '100', '1']
[WARNING:2023-02-13 18:05:38,737] rhasspynlu.slots: Failed to load file/program for slot hass/entities,switch (tried: [PosixPath('/profiles/en/slots'), PosixPath('/usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/en/slots')], [PosixPath('/profiles/en/slot_programs'), PosixPath('/usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/en/slot_programs')])
[DEBUG:2023-02-13 18:05:38,733] rhasspynlu.slots: Loading slot hass/colors from /profiles/en/slots/hass/colors
[WARNING:2023-02-13 18:05:38,733] rhasspynlu.slots: Failed to load file/program for slot hass/entities,light (tried: [PosixPath('/profiles/en/slots'), PosixPath('/usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/en/slots')], [PosixPath('/profiles/en/slot_programs'), PosixPath('/usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/en/slot_programs')])
[DEBUG:2023-02-13 18:05:38,730] rhasspynlu.ini_jsgf: Loaded ini file
[DEBUG:2023-02-13 18:05:38,728] rhasspyserver_hermes: Generating intent graph
[DEBUG:2023-02-13 18:05:38,727] rhasspyserver_hermes: Loading sentences from [PosixPath('/profiles/en/sentences.ini')]
[INFO:2023-02-13 18:05:38,726] rhasspyserver_hermes: Starting training
[DEBUG:2023-02-13 18:05:34,873] rhasspyserver_hermes: Writing /profiles/en/sentences.ini
[DEBUG:2023-02-13 17:55:10,607] rhasspyserver_hermes: <- NluIntentNotRecognized(input='', site_id='default', id=None, custom_data='Jarvis', session_id='default-Jarvis-59640bf5-7fa9-41d7-8518-75414bca92b9')
[DEBUG:2023-02-13 17:55:06,818] rhasspyserver_hermes: <- HotwordDetected(model_id='/profiles/en/raven/Jarvis/example-1.wav', model_version='', model_type='personal', current_sensitivity=0.5, site_id='default', session_id=None, send_audio_captured=None, lang=None, custom_entities=None)

**Comment by Jazz-ha** [comment]
**Relevant senstences.ini**

[HassTurnOn]
lights = $hass/entities,light
switches = $hass/entities,switch
entities = \<lights\>|\<switches\>
turn on [the] (\<entities\>){name}

[HassTurnOff]
turn off [the] (\<HassTurnOn.entities\>){name}

[HassLightSet]
set [the] (\<HassTurnOn.lights\>){name} to ($hass/colors){color} 
set [the] (\<HassTurnOn.lights\>) [brightness] to (1..100){brightness} percent

**Comment by Jazz-ha** [comment]
the first problem I found is that the script is looking for an environment variable:
profile="**_${RHASSPY_PROFILE_DIR}_**/profile.json"
replacing that with an absolute path lets the script run, but did not fix the error
