### ISSUE TITLE
Intent handler 'command' failed

### ISSUE THREAD

**Issue by markusappel** [rhasspy/rhasspy#32]
Trying to use a python script as intent handler with the 2.5.0-pre docker image fails; the same used to work in 2.4.19:

```
    "handle": {
        "command": {
            "program": "/profiles/handler.py"
        },
        "system": "command"
```

The log:
```
rhasspy    | [DEBUG:2020-04-28 20:06:00,670] rhasspyremote_http_hermes: /profiles/handler.py
rhasspy    | [ERROR:2020-04-28 20:06:00,674] rhasspyremote_http_hermes: handle_intent
rhasspy    | Traceback (most recent call last):
rhasspy    |   File "/usr/lib/rhasspy-voltron/rhasspy-remote-http-hermes/rhasspyremote_http_hermes/__init__.py", line 795, in handle_intent
rhasspy    |     stderr=asyncio.subprocess.PIPE,
rhasspy    |   File "/usr/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
rhasspy    |     stderr=stderr, **kwds)
rhasspy    |   File "/usr/lib/python3.7/asyncio/base_events.py", line 1529, in subprocess_exec
rhasspy    |     bufsize, **kwargs)
rhasspy    |   File "/usr/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
rhasspy    |     **kwargs)
rhasspy    |   File "/usr/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
rhasspy    |     stderr=stderr, bufsize=bufsize, **kwargs)
rhasspy    |   File "/usr/lib/python3.7/asyncio/unix_events.py", line 775, in _start
rhasspy    |     universal_newlines=False, bufsize=bufsize, **kwargs)
rhasspy    |   File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
rhasspy    |     restore_signals, start_new_session)
rhasspy    |   File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
rhasspy    |     raise child_exception_type(errno_num, err_msg, err_filename)
rhasspy    | PermissionError: [Errno 13] Permission denied: '/'
```

Is this a problem in `rhasspy-remote-http-hermes/rhasspyremote_http_hermes/__init__.py` or is my configuration not correct ... ?

PS: Thanks for that great project.

**Comment by synesthesiam** [comment]
Figured out the problem, thanks! A fix will be posted in the next Docker image.
