### ISSUE TITLE
Training Download fails

### ISSUE THREAD

**Issue by Rum459** [rhasspy/rhasspy#4]
Error log:
[ERROR:2020-03-21 18:21:58,957] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.6/site-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy-voltron/.venv/lib/python3.6/site-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy-voltron/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1137, in api_train
    result = await core.train()
  File "/usr/lib/rhasspy-voltron/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 367, in train
    timeout_seconds=self.training_timeout_seconds,
  File "/usr/lib/rhasspy-voltron/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 832, in publish_wait
    _, result = await asyncio.wait_for(result_awaitable, timeout_seconds)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by synesthesiam** [comment]
Hopefully fixed by now. Please re-open if the issue persists.
