### ISSUE TITLE
snowboy not working

### ISSUE THREAD

**Issue by lilbuh** [rhasspy/rhasspy#47]
hey there

on the latest docker image snowboy isn t working anymore

31/05/2020
Digest: sha256:ea229eccab38d6d7a112a4feaef47b903664971a5d8fa4750ed6b767728e8ed3
Status: Image is up to date for rhasspy/rhasspy:2.5.0-pre

here's the relevant docker log:

> 2020-05-30 11:01:37,077 WARN received SIGHUP indicating restart request
2020-05-30 11:01:37,078 INFO waiting for microphone, speakers to die
2020-05-30 11:01:38,096 INFO stopped: speakers (terminated by SIGTERM)
2020-05-30 11:01:38,110 INFO stopped: microphone (terminated by SIGTERM)
2020-05-30 11:01:38,157 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-05-30 11:01:38,159 INFO supervisord started with pid 144
2020-05-30 11:01:39,173 INFO spawned: 'microphone' with pid 625
2020-05-30 11:01:39,188 INFO spawned: 'speakers' with pid 626
2020-05-30 11:01:39,204 INFO spawned: 'wake_word' with pid 627
[DEBUG:2020-05-30 11:01:40,110] rhasspyspeakers_cli_hermes: Namespace(debug=True, host='192.168.1.100', list_command='aplay -L', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', password='EDITED', play_command='aplay -q -t wav', port=1883, site_id=['salon'], tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, username='EDITED')
[DEBUG:2020-05-30 11:01:40,115] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:40,117] rhasspyspeakers_cli_hermes: Connecting to 192.168.1.100:1883
[DEBUG:2020-05-30 11:01:40,132] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:40,135] rhasspyspeakers_cli_hermes: Connected to MQTT broker
[DEBUG:2020-05-30 11:01:40,137] rhasspyspeakers_cli_hermes: Subscribed to hermes/audioServer/salon/playBytes/#
[DEBUG:2020-05-30 11:01:40,139] rhasspyspeakers_cli_hermes: Subscribed to rhasspy/audioServer/getDevices
[DEBUG:2020-05-30 11:01:40,141] rhasspyspeakers_cli_hermes: Subscribed to hermes/audioServer/toggleOn
[DEBUG:2020-05-30 11:01:40,143] rhasspyspeakers_cli_hermes: Subscribed to hermes/audioServer/toggleOff
[DEBUG:2020-05-30 11:01:40,185] rhasspywake_snowboy_hermes: Namespace(debug=True, host='192.168.1.100', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', model=[['jarvis.umdl', '0.5,0.5', '1.0', 'True']], model_dir=['/profiles/fr/snowboy'], password='EDITED', port=1883, site_id=['salon'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio=[['localhost', '12202', 'salon']], username='EDITED', wakeword_id=None)
2020-05-30 11:01:40,186 INFO success: microphone entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-30 11:01:40,187 INFO success: speakers entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[DEBUG:2020-05-30 11:01:40,186] rhasspywake_snowboy_hermes: Loading model from jarvis.umdl
[DEBUG:2020-05-30 11:01:40,196] asyncio: Using selector: EpollSelector
2020-05-30 11:01:40,198 INFO success: wake_word entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[DEBUG:2020-05-30 11:01:40,202] rhasspywake_snowboy_hermes: Listening for audio on UDP localhost:12202
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
2020-05-30 11:01:40,375 INFO exited: wake_word (exit status 1; not expected)
[DEBUG:2020-05-30 11:01:40,656] rhasspymicrophone_cli_hermes: Namespace(channels=1, debug=True, host='192.168.1.100', list_command='arecord -L', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', output_site_id=None, password='EDITED', port=1883, record_command='arecord -q -r 16000 -f S16_LE -c 1 -t raw -D sysdefault:CARD=CameraB409241', sample_rate=16000, sample_width=2, site_id=['salon'], test_command='arecord -q -D {} -r 16000 -f S16_LE -c 1 -t raw', tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio_host='127.0.0.1', udp_audio_port=12202, username='EDITED')
2020-05-30 11:01:40,664 INFO spawned: 'wake_word' with pid 637
[DEBUG:2020-05-30 11:01:40,660] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:40,662] rhasspymicrophone_cli_hermes: Audio will also be sent to UDP 127.0.0.1:12202
[DEBUG:2020-05-30 11:01:40,667] rhasspymicrophone_cli_hermes: ['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'sysdefault:CARD=CameraB409241']
[DEBUG:2020-05-30 11:01:40,669] rhasspymicrophone_cli_hermes: Connecting to 192.168.1.100:1883
[DEBUG:2020-05-30 11:01:40,690] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:40,692] rhasspymicrophone_cli_hermes: Connected to MQTT broker
[DEBUG:2020-05-30 11:01:40,693] rhasspymicrophone_cli_hermes: Recording audio
[DEBUG:2020-05-30 11:01:40,696] rhasspymicrophone_cli_hermes: Subscribed to hermes/audioServer/toggleSummaryOn
[DEBUG:2020-05-30 11:01:40,698] rhasspymicrophone_cli_hermes: Subscribed to hermes/asr/startListening
[DEBUG:2020-05-30 11:01:40,701] rhasspymicrophone_cli_hermes: Subscribed to hermes/asr/stopListening
[DEBUG:2020-05-30 11:01:40,703] rhasspymicrophone_cli_hermes: Subscribed to rhasspy/audioServer/getDevices
[DEBUG:2020-05-30 11:01:40,705] rhasspymicrophone_cli_hermes: Subscribed to hermes/audioServer/toggleSummaryOff
[DEBUG:2020-05-30 11:01:41,472] rhasspywake_snowboy_hermes: Namespace(debug=True, host='192.168.1.100', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', model=[['jarvis.umdl', '0.5,0.5', '1.0', 'True']], model_dir=['/profiles/fr/snowboy'], password='EDITED', port=1883, site_id=['salon'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio=[['localhost', '12202', 'salon']], username='EDITED', wakeword_id=None)
[DEBUG:2020-05-30 11:01:41,474] rhasspywake_snowboy_hermes: Loading model from jarvis.umdl
[DEBUG:2020-05-30 11:01:41,478] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:41,483] rhasspywake_snowboy_hermes: Listening for audio on UDP localhost:12202
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
[ERROR:2020-05-30 11:01:41,512] rhasspywake_snowboy_hermes: detection_thread_proc
Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 221, in detection_thread_proc
    self.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
2020-05-30 11:01:41,638 INFO exited: wake_word (exit status 1; not expected)
2020-05-30 11:01:42,646 INFO spawned: 'wake_word' with pid 646
[DEBUG:2020-05-30 11:01:43,646] rhasspywake_snowboy_hermes: Namespace(debug=True, host='192.168.1.100', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', model=[['jarvis.umdl', '0.5,0.5', '1.0', 'True']], model_dir=['/profiles/fr/snowboy'], password='EDITED', port=1883, site_id=['salon'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio=[['localhost', '12202', 'salon']], username='EDITED', wakeword_id=None)
2020-05-30 11:01:43,648 INFO success: wake_word entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[DEBUG:2020-05-30 11:01:43,649] rhasspywake_snowboy_hermes: Loading model from jarvis.umdl
[DEBUG:2020-05-30 11:01:43,653] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:43,657] rhasspywake_snowboy_hermes: Listening for audio on UDP localhost:12202
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
[ERROR:2020-05-30 11:01:43,687] rhasspywake_snowboy_hermes: detection_thread_proc
Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 221, in detection_thread_proc
    self.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
2020-05-30 11:01:43,812 INFO exited: wake_word (exit status 1; not expected)
2020-05-30 11:01:44,819 INFO spawned: 'wake_word' with pid 651
[DEBUG:2020-05-30 11:01:45,671] rhasspywake_snowboy_hermes: Namespace(debug=True, host='192.168.1.100', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', model=[['jarvis.umdl', '0.5,0.5', '1.0', 'True']], model_dir=['/profiles/fr/snowboy'], password='EDITED', port=1883, site_id=['salon'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio=[['localhost', '12202', 'salon']], username='EDITED', wakeword_id=None)
[DEBUG:2020-05-30 11:01:45,673] rhasspywake_snowboy_hermes: Loading model from jarvis.umdl
[DEBUG:2020-05-30 11:01:45,678] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:45,684] rhasspywake_snowboy_hermes: Listening for audio on UDP localhost:12202
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
[ERROR:2020-05-30 11:01:45,715] rhasspywake_snowboy_hermes: detection_thread_proc
Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 221, in detection_thread_proc
    self.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
2020-05-30 11:01:45,844 INFO success: wake_word entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-30 11:01:45,844 INFO exited: wake_word (exit status 1; not expected)
2020-05-30 11:01:46,851 INFO spawned: 'wake_word' with pid 656
[DEBUG:2020-05-30 11:01:47,610] rhasspywake_snowboy_hermes: Namespace(debug=True, host='192.168.1.100', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', model=[['jarvis.umdl', '0.5,0.5', '1.0', 'True']], model_dir=['/profiles/fr/snowboy'], password='EDITED', port=1883, site_id=['salon'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio=[['localhost', '12202', 'salon']], username='EDITED', wakeword_id=None)
[DEBUG:2020-05-30 11:01:47,611] rhasspywake_snowboy_hermes: Loading model from jarvis.umdl
[DEBUG:2020-05-30 11:01:47,616] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:47,622] rhasspywake_snowboy_hermes: Listening for audio on UDP localhost:12202
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
[ERROR:2020-05-30 11:01:47,652] rhasspywake_snowboy_hermes: detection_thread_proc
Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 221, in detection_thread_proc
    self.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
2020-05-30 11:01:47,777 INFO exited: wake_word (exit status 1; not expected)
2020-05-30 11:01:48,784 INFO spawned: 'wake_word' with pid 661
[DEBUG:2020-05-30 11:01:49,596] rhasspywake_snowboy_hermes: Namespace(debug=True, host='192.168.1.100', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', model=[['jarvis.umdl', '0.5,0.5', '1.0', 'True']], model_dir=['/profiles/fr/snowboy'], password='EDITED', port=1883, site_id=['salon'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio=[['localhost', '12202', 'salon']], username='EDITED', wakeword_id=None)
[DEBUG:2020-05-30 11:01:49,597] rhasspywake_snowboy_hermes: Loading model from jarvis.umdl
[DEBUG:2020-05-30 11:01:49,601] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:49,622] rhasspywake_snowboy_hermes: Listening for audio on UDP localhost:12202
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
[ERROR:2020-05-30 11:01:49,636] rhasspywake_snowboy_hermes: detection_thread_proc
Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 221, in detection_thread_proc
    self.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
2020-05-30 11:01:49,758 INFO exited: wake_word (exit status 1; not expected)
2020-05-30 11:01:51,767 INFO spawned: 'wake_word' with pid 666
[DEBUG:2020-05-30 11:01:52,522] rhasspywake_snowboy_hermes: Namespace(debug=True, host='192.168.1.100', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', model=[['jarvis.umdl', '0.5,0.5', '1.0', 'True']], model_dir=['/profiles/fr/snowboy'], password='EDITED', port=1883, site_id=['salon'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio=[['localhost', '12202', 'salon']], username='EDITED', wakeword_id=None)
[DEBUG:2020-05-30 11:01:52,523] rhasspywake_snowboy_hermes: Loading model from jarvis.umdl
[DEBUG:2020-05-30 11:01:52,527] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:52,532] rhasspywake_snowboy_hermes: Listening for audio on UDP localhost:12202
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
[ERROR:2020-05-30 11:01:52,562] rhasspywake_snowboy_hermes: detection_thread_proc
Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 221, in detection_thread_proc
    self.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
2020-05-30 11:01:52,685 INFO exited: wake_word (exit status 1; not expected)
2020-05-30 11:01:55,695 INFO spawned: 'wake_word' with pid 671
[DEBUG:2020-05-30 11:01:56,515] rhasspywake_snowboy_hermes: Namespace(debug=True, host='192.168.1.100', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', model=[['jarvis.umdl', '0.5,0.5', '1.0', 'True']], model_dir=['/profiles/fr/snowboy'], password='EDITED', port=1883, site_id=['salon'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, udp_audio=[['localhost', '12202', 'salon']], username='EDITED', wakeword_id=None)
[DEBUG:2020-05-30 11:01:56,518] rhasspywake_snowboy_hermes: Loading model from jarvis.umdl
[DEBUG:2020-05-30 11:01:56,522] asyncio: Using selector: EpollSelector
[DEBUG:2020-05-30 11:01:56,545] rhasspywake_snowboy_hermes: Listening for audio on UDP localhost:12202
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing jarvis.umdl
2020-05-30 11:01:56,679 INFO exited: wake_word (exit status 1; not expected)
2020-05-30 11:01:57,681 INFO gave up: wake_word entered FATAL state, too many start retries too quickly

**Comment by lilbuh** [comment]
kinda found a workaround
i copied the jarvis.umdl file from the [repo](https://github.com/Kitt-AI/snowboy/blob/master/resources/models/jarvis.umdl)
and in the snowboy settings i entered the FULL path in the Model textbox:

/profiles/fr/snowboy/jarvis.umdl

still cant refresh the available hotwords

**Comment by synesthesiam** [comment]
Hmmm...it should look in the `snowboy` directory in your profile first for models. The fallback is to try and interpret the model name as a full file path, so I'm glad this is working for you.
