### ISSUE TITLE
Settings page does not load

### ISSUE THREAD

**Issue by FlorinAcsinte** [rhasspy/rhasspy#66]
Hi. Just installed Rhasspy 2.5 on a laptop with the venv method. 

Looks like no services are started, as mentioned in the documentation. However, i cannot go into settings to enable them. 
When going to settings, i get the following error in the terminal:
`
[ERROR:2020-06-13 22:46:29,648] rhasspyserver_hermes: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/rhasspyserver_hermes/__main__.py", line 2413, in page_settings
    "settings.html", page="Settings", **get_template_args()
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/templating.py", line 91, in render_template
    return await _render(template, context)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/templating.py", line 109, in _render
    rendered_template = await template.render_async(context)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 65, in render_async
    return self.environment.handle_exception()
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 25, in concat_async
    await collect()
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 22, in collect
    async for event in async_gen:
  File "/home/bugsbunny/rhasspy/.venv/share/rhasspy/templates/settings.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/bugsbunny/rhasspy/.venv/share/rhasspy/templates/layout.html", line 157, in top-level template code
    {% block body %}{% endblock %}
  File "/home/bugsbunny/rhasspy/.venv/share/rhasspy/templates/settings.html", line 882, in block "body"
    <li>Base Language Model FST: <tt>{{ profile.read_path(profile.get("speech_to_text.pocketsphinx.base_language_model_fst")) }}</tt> </li>
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/rhasspyprofile/profile.py", line 125, in read_path
    full_path = profiles_dir.joinpath(self.name, *path_parts)
  File "/usr/lib/python3.7/pathlib.py", line 905, in joinpath
    return self._make_child(args)
  File "/usr/lib/python3.7/pathlib.py", line 695, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.7/pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR:2020-06-13 22:46:29,765] rhasspyserver_hermes: NotFound(404)
Traceback (most recent call last):
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1863, in dispatch_request
    raise request_.routing_exception
quart.exceptions.NotFound: NotFound(404)
`
Also, the 'docs' page fails to load with the following error:
`

[ERROR:2020-06-13 22:50:38,348] rhasspyserver_hermes: NotFound(404)
Traceback (most recent call last):
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/static.py", line 128, in safe_join
    safe_path = file_path_to_path(directory).resolve(strict=True)
  File "/usr/lib/python3.7/pathlib.py", line 1151, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "/usr/lib/python3.7/pathlib.py", line 355, in resolve
    return _resolve(base, str(path)) or sep
  File "/usr/lib/python3.7/pathlib.py", line 339, in _resolve
    target = accessor.readlink(newpath)
  File "/usr/lib/python3.7/pathlib.py", line 437, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/bugsbunny/rhasspy/.venv/share/rhasspy/web/docs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/rhasspyserver_hermes/__main__.py", line 2365, in docs_index
    return await send_from_directory(docs_dir, "index.html")
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/static.py", line 161, in send_from_directory
    file_path = safe_join(directory, file_name)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/static.py", line 131, in safe_join
    raise NotFound()
quart.exceptions.NotFound: NotFound(404)
[ERROR:2020-06-13 22:50:38,478] rhasspyserver_hermes: NotFound(404)
Traceback (most recent call last):
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/bugsbunny/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1863, in dispatch_request
    raise request_.routing_exception
quart.exceptions.NotFound: NotFound(404)
`

**Comment by synesthesiam** [comment]
I think I've located the problem. Should be fixed in the next version.

**Comment by Romkabouter** [comment]
Related to https://github.com/rhasspy/rhasspy-server-hermes/issues/9

**Comment by synesthesiam** [comment]
This should be fixed now with a function that returns an empty string during rendering if there's an error on the settings page.
