### ISSUE TITLE
snowboy dosen't work - timeout

### ISSUE THREAD

**Issue by DerT94** [rhasspy/rhasspy#86]
When I try to refresh the Snowboy models, I get a timeout error.

**profile.json**
```
{
    "intent": {
        "remote": {
            "url": "http://rhasspy.example.loc:12101/api/text-to-intent"
        },
        "system": "remote"
    },
    "microphone": {
        "system": "pyaudio"
    },
    "mqtt": {
        "enabled": "true",
        "host": "rhasspy.example.loc",
        "site_id": "testpi"
    },
    "sounds": {
        "aplay": {
            "device": "default:CARD=seeed2micvoicec"
        },
        "system": "aplay"
    },
    "speech_to_text": {
        "remote": {
            "url": "http://rhasspy.example.loc:12101/api/speech-to-text"
        },
        "system": "remote"
    },
    "text_to_speech": {
        "remote": {
            "url": "http://rhasspy.example.loc:12101/api/text-to-speech"
        },
        "system": "remote"
    },
    "wake": {
        "snowboy": {
            "model": "computer.umdl"
        },
        "system": "snowboy"
    }
}
```

**Log**
```
[ERROR:2020-07-14 16:51:07,929] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyserver_hermes/__main__.py", line 728, in api_wake_words
    hotwords = await core.get_hotwords()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyserver_hermes/__init__.py", line 814, in get_hotwords
    handle_finished(), messages, message_types
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyserver_hermes/__init__.py", line 898, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[DEBUG:2020-07-14 16:50:37,925] rhasspyserver_hermes: Publishing 66 bytes(s) to rhasspy/hotword/getHotwords
[DEBUG:2020-07-14 16:50:37,924] rhasspyserver_hermes: -> GetHotwords(site_id='testpi', id='a8c232a8-e5bc-4d27-9d6f-1e3ae7cd54fc')
[DEBUG:2020-07-14 16:50:37,922] rhasspyserver_hermes: Subscribed to rhasspy/hotword/hotwords
```

![image](https://user-images.githubusercontent.com/58786605/87453745-4733cc80-c603-11ea-8cf7-b728d963aae3.png)

**Comment by synesthesiam** [comment]
What hardware are you running on? Also, do you see any errors from the snowboy service when starting up?

**Comment by DerT94** [comment]
First I used a raspberry pi 3 and now a raspberry pi 4.
The problem occures on both.
Were can I find the snowboy logs?

**Comment by synesthesiam** [comment]
They should be printed to the console along with the other service logs, but prefixed with something like "rhasspy-wake-snowboy-hermes". If you're running this in Docker, you can do `docker run -it ...` instead of `docker run -d ...` or check out something like portainer.

**Comment by DerT94** [comment]
Hi,

I found the error.
Apparently the snowboy service will not load if the file is not present.

In my case I had a typo "computer.umdl" --> "computer.pmdl".
After I adjusted the profile.json it worked.

Now the refresh also works.

But the snowboy.pmdl, which is the default value, was never there and therefore the service was not started.

**LOG**
```
[DEBUG:2020-07-27 09:29:26,031] rhasspywake_snowboy_hermes: Loading model from computer.umdl
[DEBUG:2020-07-27 09:29:26,034] asyncio: Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/lib/rhasspy/bin/rhasspy-wake-snowboy-hermes", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__main__.py", line 138, in main
    hermes.load_detectors()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspywake_snowboy_hermes/__init__.py", line 126, in load_detectors
    assert model.model_path.is_file(), f"Missing {model.model_path}"
AssertionError: Missing computer.umdl
```
