### ISSUE TITLE
no output if mopidy was running

### ISSUE THREAD

**Issue by DerT94** [rhasspy/rhasspy#90]
Hi,

I have installed rhasspy and mopidy on a RaspberryPi 4
Both systems work well separately.

But as soon as I play music on mopidy the voice output in rhasspy does not work anymore.
The error remains until the RPI is restarted.
Even if the mopidy service is stopped.

Unfortunately I can't see anything in the rhasspy logs.

```
[DEBUG:2020-07-22 09:10:55,500] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=fb51a3ac-70d0-4808-99be-90838cc9e3fa)
[DEBUG:2020-07-22 09:10:55,498] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/testpi/playBytes/e1ec6455-8b1f-4f83-a8fc-e7c479485d66, id=fb51a3ac-70d0-4808-99be-90838cc9e3fa)
[DEBUG:2020-07-22 09:10:54,489] rhasspyserver_hermes: Publishing 113 bytes(s) to hermes/tts/say
[DEBUG:2020-07-22 09:10:54,489] rhasspyserver_hermes: -> TtsSay(text='Test', site_id='testpi', lang=None, id='e1ec6455-8b1f-4f83-a8fc-e7c479485d66', session_id='')

```

When I type the command `aplay /usr/share/sounds/alsa/Front_Center.wav` directly in the console I hear an output.

**Comment by synesthesiam** [comment]
Is Rhasspy running inside Docker? If so, it's using ALSA and may be conflicting with pulseaudio on the local system.

**Comment by DerT94** [comment]
Hey,

yes I'm using docker.
How can I check this?
Do you have any suggestions on how I can solve this problem?

**Comment by DerT94** [comment]
Now i get an error message
```
[ERROR:2020-07-28 08:24:16,703] rhasspyserver_hermes: Command '['aplay', '-q', '-t', 'wav', '-D', 'aplay']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1541, in api_play_recording
    await core.play_wav_data(wav_bytes)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 725, in play_wav_data
    raise RuntimeError(result.error)
RuntimeError: Command '['aplay', '-q', '-t', 'wav', '-D', 'aplay']' returned non-zero exit status 1.
```

**Comment by DerT94** [comment]
If i run the container bash and try "play /usr/share/sounds/alsa/Front_Center.wav" I get the follwoing error.
"aplay: main:828: audio open error: Device or resource busy"

The container was started with the command "--device /dev/snd".
Did I pass the wrong device here?

In my asound.conf it is configured via dmix.

What do I have to pass to use the mixer?

**asound.conf**
```
# use samplerate to resample as speexdsp resample is bad
defaults.pcm.rate_converter "samplerate"

pcm.!default {
    type asym
    playback.pcm "playback"
    capture.pcm "capture"
}

pcm.playback {
    type plug
    slave.pcm "dmixed"
}

pcm.capture {
    type plug
    slave.pcm "array"
}

pcm.dmixed {
    type dmix
    ipc_perm 0666
    slave.pcm "hw:seeed2micvoicec"
    ipc_key 555555
}

pcm.array {
    type dsnoop
    slave {
        pcm "hw:seeed2micvoicec"
        channels 2
    }
    ipc_key 666666
}





```

**Comment by Xalip** [comment]
Isn't this post simliar to your issue?

[Rhasspy Forum](https://community.rhasspy.org/t/stream-music-or-radio/497)

**Comment by Xalip** [comment]
Did my linked post solve your issue?

**Comment by DerT94** [comment]
Sorry I've forgotten to answer.

Not directly, but I found this thread and got help there.

For all others who have the problem.

1. Create two playback devices in alsa asound.conf and dmix them to given HW card (one is for Rhasspy playback TTS and second for music playback - in my case mopidy client)
2. Share same asound.conf between host and Rhasspy Docker container
3. Share host IPC Rhasspy Docker container


**asound.conf**
```
pcm.mopidy {
    type plug
    slave.pcm "mopidy_vol"
}


pcm.mopidy_vol {
    type softvol
    slave.pcm "mix"
    control {
        name "mopidy"
        card 0
    }
}

pcm.rhasspy {
    type plug
    slave.pcm "rhasspy_vol"
}


pcm.rhasspy_vol {
    type softvol
    slave.pcm "mix"
    control {
        name "Rhasspy"
        card 0
    }
}

pcm.mix {
    type dmix
    ipc_key 1024
    ipc_perm 0666
    slave {
        pcm "hw:seeed2micvoicec"
        period_time 0
        period_size 1024
        buffer_size 4096
        rate 48000
        format S24_3LE
    }
    bindings {
        0 0
        1 1
    }
}

pcm.capture {
    type plug
    slave.pcm "array"
}

pcm.array {
    type dsnoop
    slave {
        pcm "hw:seeed2micvoicec"
        channels 2
    }
    ipc_key 666666
}
```

**docker run command**
```
docker run -d -p 12101:12101
           --name rhasspy \
           --restart unless-stopped \
           -v "$HOME/.config/rhasspy/profiles:/profiles" \
           -v "/etc/localtime:/etc/localtime:ro" \
           -v "/etc/asound.conf:/etc/asound.conf" \
           --device /dev/snd:/dev/snd \
           --ipc="host" \
           rhasspy/rhasspy --user-profiles /profiles  --profile en
```
